-- Add more publications (batch 7) - IDs 590-649
INSERT INTO public.publications (
  external_id, name, type, tier, category, price, tat_days, description, features, 
  website_url, da_score, dr_score, location, dofollow_link, sponsored, indexed,
  erotic, health, cbd, crypto, gambling, popularity, is_active
) VALUES
-- Travel & Hospitality Publications (590-599)
('pub_590', 'Travel + Leisure', 'tier1', 'tier1', 'Travel', 2100, '4-6 days', 'Premier travel magazine', '{"Travel", "Hotels", "Destinations"}', 'https://travelandleisure.com', 85, 82, 'United States', true, false, true, false, false, false, false, false, 87, true),
('pub_591', 'Conde Nast Traveler', 'premium', 'premium', 'Travel', 3800, '5-8 days', 'Luxury travel publication', '{"Luxury Travel", "Hotels", "Destinations"}', 'https://cntraveler.com', 88, 85, 'United States', true, false, true, false, false, false, false, false, 90, true),
('pub_592', 'Lonely Planet', 'tier1', 'tier1', 'Travel', 1900, '3-5 days', 'Travel guide publisher', '{"Travel Guides", "Destinations", "Adventure"}', 'https://lonelyplanet.com', 82, 79, 'Australia', true, false, true, false, false, false, false, false, 84, true),
('pub_593', 'National Geographic Travel', 'premium', 'premium', 'Travel', 4200, '6-8 days', 'Adventure and cultural travel', '{"Adventure Travel", "Culture", "Photography"}', 'https://nationalgeographic.com/travel', 91, 88, 'United States', true, false, true, false, false, false, false, false, 93, true),
('pub_594', 'Budget Travel', 'tier2', 'tier2', 'Travel', 1200, '3-5 days', 'Affordable travel tips', '{"Budget Travel", "Tips", "Destinations"}', 'https://budgettravel.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_595', 'Fodors Travel', 'tier2', 'tier2', 'Travel', 1400, '4-6 days', 'Travel guides and tips', '{"Travel Guides", "Hotels", "Restaurants"}', 'https://fodors.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_596', 'TripSavvy', 'tier2', 'tier2', 'Travel', 1100, '2-4 days', 'Travel planning resource', '{"Travel Planning", "Tips", "Guides"}', 'https://tripsavvy.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_597', 'Afar Magazine', 'tier1', 'tier1', 'Travel', 1800, '4-6 days', 'Experiential travel magazine', '{"Cultural Travel", "Experiences", "Local Culture"}', 'https://afar.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_598', 'Outside Magazine', 'tier1', 'tier1', 'Travel', 1700, '3-5 days', 'Outdoor adventure magazine', '{"Adventure", "Outdoors", "Travel"}', 'https://outsidemagazine.com', 77, 74, 'United States', true, false, true, false, false, false, false, false, 79, true),
('pub_599', 'Skift Travel', 'tier2', 'tier2', 'Travel', 1300, '2-4 days', 'Travel industry news', '{"Travel Industry", "Business Travel", "Tourism"}', 'https://skift.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),

-- Food & Beverage Publications (600-609)
('pub_600', 'Food & Wine', 'tier1', 'tier1', 'Food', 2000, '4-6 days', 'Culinary arts magazine', '{"Food", "Wine", "Recipes"}', 'https://foodandwine.com', 83, 80, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_601', 'Bon Appetit', 'tier1', 'tier1', 'Food', 2200, '4-6 days', 'Food and cooking magazine', '{"Cooking", "Restaurants", "Food Culture"}', 'https://bonappetit.com', 84, 81, 'United States', true, false, true, false, false, false, false, false, 86, true),
('pub_602', 'Eater', 'tier1', 'tier1', 'Food', 1800, '2-4 days', 'Food and restaurant news', '{"Restaurant News", "Food Culture", "Dining"}', 'https://eater.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),
('pub_603', 'Food Network Magazine', 'tier2', 'tier2', 'Food', 1500, '3-5 days', 'Food Network publication', '{"Recipes", "Cooking Shows", "Celebrity Chefs"}', 'https://foodnetwork.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_604', 'Saveur', 'tier1', 'tier1', 'Food', 1900, '4-6 days', 'Authentic world cuisine', '{"World Cuisine", "Culture", "Travel"}', 'https://saveur.com', 80, 77, 'United States', true, false, true, false, false, false, false, false, 82, true),
('pub_605', 'Cooking Light', 'tier2', 'tier2', 'Food', 1300, '3-5 days', 'Healthy cooking magazine', '{"Healthy Recipes", "Nutrition", "Wellness"}', 'https://cookinglight.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_606', 'Wine Spectator', 'tier1', 'tier1', 'Food', 2100, '5-7 days', 'Wine industry publication', '{"Wine", "Wine Reviews", "Vineyards"}', 'https://winespectator.com', 82, 79, 'United States', true, false, true, false, false, false, false, false, 84, true),
('pub_607', 'Serious Eats', 'tier2', 'tier2', 'Food', 1200, '2-4 days', 'Food science and cooking', '{"Food Science", "Recipes", "Cooking Techniques"}', 'https://seriouseats.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_608', 'Epicurious', 'tier2', 'tier2', 'Food', 1100, '3-5 days', 'Recipe and cooking resource', '{"Recipes", "Cooking Tips", "Food"}', 'https://epicurious.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_609', 'Delish', 'tier2', 'tier2', 'Food', 1000, '2-4 days', 'Fun food content', '{"Easy Recipes", "Food Trends", "Cooking"}', 'https://delish.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),

-- Sports Publications (610-619)
('pub_610', 'ESPN', 'tier1', 'tier1', 'Sports', 2500, '1-3 days', 'Leading sports network', '{"Sports News", "Live Updates", "Analysis"}', 'https://espn.com', 90, 87, 'United States', true, false, true, false, false, false, false, false, 92, true),
('pub_611', 'Sports Illustrated', 'tier1', 'tier1', 'Sports', 2300, '3-5 days', 'Premier sports magazine', '{"Sports Features", "Analysis", "Athletes"}', 'https://si.com', 86, 83, 'United States', true, false, true, false, false, false, false, false, 88, true),
('pub_612', 'The Athletic', 'premium', 'premium', 'Sports', 3200, '2-4 days', 'Premium sports journalism', '{"In-depth Sports", "Analysis", "Local Coverage"}', 'https://theathletic.com', 84, 81, 'United States', true, false, true, false, false, false, false, false, 86, true),
('pub_613', 'Bleacher Report', 'tier2', 'tier2', 'Sports', 1400, '1-2 days', 'Sports news and analysis', '{"Sports News", "Fantasy Sports", "Social"}', 'https://bleacherreport.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_614', 'CBS Sports', 'tier1', 'tier1', 'Sports', 2000, '1-3 days', 'CBS sports coverage', '{"Sports News", "Scores", "Analysis"}', 'https://cbssports.com', 83, 80, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_615', 'Fox Sports', 'tier1', 'tier1', 'Sports', 1900, '1-3 days', 'Fox sports network', '{"Sports News", "Live Coverage", "Analysis"}', 'https://foxsports.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),
('pub_616', 'NFL.com', 'tier1', 'tier1', 'Sports', 2200, '1-2 days', 'Official NFL website', '{"NFL News", "Player Stats", "Game Coverage"}', 'https://nfl.com', 87, 84, 'United States', true, false, true, false, false, false, false, false, 89, true),
('pub_617', 'NBA.com', 'tier1', 'tier1', 'Sports', 2100, '1-2 days', 'Official NBA website', '{"NBA News", "Player Stats", "Game Coverage"}', 'https://nba.com', 85, 82, 'United States', true, false, true, false, false, false, false, false, 87, true),
('pub_618', 'MLB.com', 'tier1', 'tier1', 'Sports', 1800, '1-3 days', 'Official MLB website', '{"MLB News", "Stats", "Game Coverage"}', 'https://mlb.com', 84, 81, 'United States', true, false, true, false, false, false, false, false, 86, true),
('pub_619', 'Yahoo Sports', 'tier2', 'tier2', 'Sports', 1500, '1-2 days', 'Yahoo sports coverage', '{"Sports News", "Fantasy Sports", "Scores"}', 'https://sports.yahoo.com', 82, 79, 'United States', true, false, true, false, false, false, false, false, 84, true),

-- Education Publications (620-629)
('pub_620', 'Education Week', 'tier2', 'tier2', 'Education', 1400, '4-6 days', 'K-12 education news', '{"K-12 Education", "Policy", "Teaching"}', 'https://edweek.org', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_621', 'Inside Higher Ed', 'tier2', 'tier2', 'Education', 1300, '3-5 days', 'Higher education news', '{"Higher Education", "University News", "Research"}', 'https://insidehighered.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_622', 'Chronicle of Higher Education', 'tier1', 'tier1', 'Education', 1800, '4-6 days', 'University and college news', '{"Higher Education", "Academic Research", "Faculty"}', 'https://chronicle.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_623', 'EdTech Magazine', 'tier2', 'tier2', 'Education', 1200, '3-5 days', 'Educational technology', '{"EdTech", "Digital Learning", "Innovation"}', 'https://edtechmagazine.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_624', 'Campus Technology', 'tier2', 'tier2', 'Education', 1100, '4-6 days', 'Higher ed technology', '{"Higher Ed Tech", "IT", "Digital Campus"}', 'https://campustechnology.com', 71, 68, 'United States', true, false, true, false, false, false, false, false, 73, true),
('pub_625', 'eSchool News', 'tier2', 'tier2', 'Education', 1000, '3-5 days', 'K-12 technology news', '{"K-12 Tech", "Educational Innovation", "Digital Learning"}', 'https://eschoolnews.com', 70, 67, 'United States', true, false, true, false, false, false, false, false, 72, true),
('pub_626', 'University Business', 'tier2', 'tier2', 'Education', 1300, '4-6 days', 'Higher education business', '{"University Management", "Higher Ed Business", "Operations"}', 'https://universitybusiness.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),
('pub_627', 'THE World University Rankings', 'premium', 'premium', 'Education', 3000, '5-8 days', 'University rankings publication', '{"University Rankings", "Higher Education", "Research"}', 'https://timeshighereducation.com', 85, 82, 'United Kingdom', true, false, true, false, false, false, false, false, 87, true),
('pub_628', 'Diverse Issues in Higher Education', 'tier2', 'tier2', 'Education', 1400, '4-6 days', 'Diversity in higher education', '{"Diversity", "Higher Education", "Inclusion"}', 'https://diverseeducation.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_629', 'Faculty Focus', 'tier2', 'tier2', 'Education', 1200, '3-5 days', 'Higher education teaching', '{"Teaching", "Faculty Development", "Pedagogy"}', 'https://facultyfocus.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),

-- Real Estate Publications (630-639)
('pub_630', 'Realtor Magazine', 'tier1', 'tier1', 'Real Estate', 1700, '3-5 days', 'Real estate industry magazine', '{"Real Estate", "Property", "Market Trends"}', 'https://realtormag.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_631', 'Inman News', 'tier1', 'tier1', 'Real Estate', 1600, '2-4 days', 'Real estate news', '{"Real Estate News", "Property Technology", "Market Analysis"}', 'https://inman.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_632', 'RealtyTrac', 'tier2', 'tier2', 'Real Estate', 1200, '3-5 days', 'Foreclosure and property data', '{"Property Data", "Foreclosures", "Market Reports"}', 'https://realtytrac.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_633', 'Multi-Housing News', 'tier2', 'tier2', 'Real Estate', 1300, '4-6 days', 'Multifamily housing news', '{"Multifamily Housing", "Apartments", "Property Management"}', 'https://multihousingnews.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_634', 'Commercial Property Executive', 'tier2', 'tier2', 'Real Estate', 1400, '3-5 days', 'Commercial real estate', '{"Commercial Real Estate", "Office Buildings", "Retail"}', 'https://cpexecutive.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),
('pub_635', 'National Real Estate Investor', 'tier2', 'tier2', 'Real Estate', 1500, '4-6 days', 'Real estate investment', '{"Real Estate Investment", "REITs", "Property Development"}', 'https://nreionline.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_636', 'Real Estate Forum', 'tier2', 'tier2', 'Real Estate', 1100, '3-5 days', 'Real estate industry forum', '{"Real Estate Industry", "Market Analysis", "Investment"}', 'https://realestateforums.com', 71, 68, 'United States', true, false, true, false, false, false, false, false, 73, true),
('pub_637', 'GlobeSt', 'tier2', 'tier2', 'Real Estate', 1300, '2-4 days', 'Commercial real estate news', '{"Commercial Real Estate", "Industry News", "Market Data"}', 'https://globest.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_638', 'Housing Wire', 'tier2', 'tier2', 'Real Estate', 1200, '2-4 days', 'Housing industry news', '{"Housing Market", "Mortgage", "Real Estate Finance"}', 'https://housingwire.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),
('pub_639', 'Mortgage Professional America', 'tier2', 'tier2', 'Real Estate', 1000, '3-5 days', 'Mortgage industry publication', '{"Mortgage", "Lending", "Real Estate Finance"}', 'https://mpamag.com', 70, 67, 'United States', true, false, true, false, false, false, false, false, 72, true),

-- Automotive Publications (640-649)
('pub_640', 'Car and Driver', 'tier1', 'tier1', 'Automotive', 1800, '3-5 days', 'Automotive enthusiast magazine', '{"Car Reviews", "Automotive News", "Performance"}', 'https://caranddriver.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),
('pub_641', 'Motor Trend', 'tier1', 'tier1', 'Automotive', 1700, '3-5 days', 'Automotive magazine', '{"Car Reviews", "Auto Shows", "Industry News"}', 'https://motortrend.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_642', 'Road & Track', 'tier1', 'tier1', 'Automotive', 1600, '3-5 days', 'Performance car magazine', '{"Performance Cars", "Racing", "Automotive Culture"}', 'https://roadandtrack.com', 77, 74, 'United States', true, false, true, false, false, false, false, false, 79, true),
('pub_643', 'Automotive News', 'tier1', 'tier1', 'Automotive', 2000, '2-4 days', 'Auto industry news', '{"Auto Industry", "Manufacturing", "Sales Data"}', 'https://autonews.com', 82, 79, 'United States', true, false, true, false, false, false, false, false, 84, true),
('pub_644', 'Kelley Blue Book', 'tier2', 'tier2', 'Automotive', 1400, '3-5 days', 'Vehicle valuation and reviews', '{"Car Values", "Reviews", "Buying Guides"}', 'https://kbb.com', 84, 81, 'United States', true, false, true, false, false, false, false, false, 86, true),
('pub_645', 'Edmunds', 'tier2', 'tier2', 'Automotive', 1300, '2-4 days', 'Car buying and reviews', '{"Car Reviews", "Buying Guides", "Pricing"}', 'https://edmunds.com', 83, 80, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_646', 'AutoWeek', 'tier2', 'tier2', 'Automotive', 1200, '3-5 days', 'Automotive weekly magazine', '{"Auto News", "Racing", "Classic Cars"}', 'https://autoweek.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_647', 'Cars.com', 'tier2', 'tier2', 'Automotive', 1500, '2-4 days', 'Car shopping platform', '{"Car Shopping", "Reviews", "Automotive News"}', 'https://cars.com', 80, 77, 'United States', true, false, true, false, false, false, false, false, 82, true),
('pub_648', 'CarGurus', 'tier2', 'tier2', 'Automotive', 1100, '3-5 days', 'Car research platform', '{"Car Research", "Market Analysis", "Reviews"}', 'https://cargurus.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_649', 'WardsAuto', 'tier2', 'tier2', 'Automotive', 1300, '4-6 days', 'Automotive industry intelligence', '{"Auto Industry", "Manufacturing", "Technology"}', 'https://wardsauto.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true);