-- Add more publications (500-300 price range)
INSERT INTO publications (name, price, da_score, dr_score, category, tat_days, sponsored, indexed, dofollow_link, location, erotic, health, cbd, crypto, gambling, tier, type, is_active, popularity) VALUES
('Adapt Network', 500.00, 72, 71, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Australian Times', 500.00, 56, 55, 'News', '3-5 Days', false, true, true, 'AUSTRALIA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Business Insight', 500.00, 38, 1, 'News', '1-3 Days', true, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Deal Magazine', 500.00, 58, 3, 'News', '3-5 Days', true, true, false, 'GLOBAL', false, false, true, true, false, 'tier1', 'standard', true, 10),
('Digital Music News', 500.00, 76, 77, 'Music', '1 Week', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('EarMilk', 500.00, 60, 72, 'Music', '1-2 Weeks', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Editors Beauty', 500.00, 19, 34, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Indie Hackers', 500.00, 54, 80, 'News', '3-5 Days', false, true, false, 'UNITED STATES', true, true, true, true, true, 'tier1', 'standard', true, 10),
('MSN', 500.00, 94, 92, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Rap Reviews', 500.00, 50, 44, 'Music', '1-3 Days', false, true, true, 'GLOBAL', true, true, true, false, false, 'tier1', 'standard', true, 10),
('The Santa Clarita Valley Signal', 500.00, 76, 75, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, true, true, true, false, 'tier1', 'standard', true, 10),
('The Source', 500.00, 82, 75, 'Music', '1 Week', false, true, false, 'UNITED STATES', true, true, true, true, true, 'tier1', 'standard', true, 10),
('Washington Independent', 500.00, 61, 71, 'News', '3-5 Days', false, true, true, 'WASHINGTON DC', false, true, false, false, false, 'tier1', 'standard', true, 10),
('1883 Magazine', 400.00, 53, 62, 'News', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('AllHipHop', 400.00, 73, 73, 'Music', '3 Days', false, true, false, 'GLOBAL', false, true, true, true, false, 'tier1', 'standard', true, 10),
('Anglotopia', 400.00, 62, 56, 'News', '3 Days', false, true, true, 'ILLINOIS', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Art Daily', 400.00, 65, 79, 'Entertainment', '1-3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Deadline New', 400.00, 74, 68, 'News', '3 Days', false, true, false, 'GLOBAL', false, true, true, true, true, 'tier1', 'standard', true, 10),
('EDM Sauce', 400.00, 76, 60, 'Music', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Fine Homes and Living', 400.00, 44, 63, 'Real Estate', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Good Men Project', 400.00, 82, 79, 'News', '1 Week', false, true, true, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Home Town Station', 400.00, 66, 75, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('I Love South Africa', 400.00, 18, 56, 'News', '3-5 Days', false, true, true, 'AFRICA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('IB Times (AP)', 400.00, 73, 72, 'Business', '1 Week', false, true, false, 'ASIA PACIFIC', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Magnetic Mag', 400.00, 75, 70, 'Music', '3 Days', true, true, false, 'GLOBAL', false, false, true, false, false, 'tier1', 'standard', true, 10),
('Mom The Mag', 400.00, 56, 35, 'Lifestyle', '1-3 Days', false, true, false, 'UNITED STATES', false, true, true, false, false, 'tier1', 'standard', true, 10),
('Neon Music', 400.00, 63, 58, 'Music', '3-5 Days', false, true, true, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('NY Tech Media', 400.00, 34, 34, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Patch.com', 400.00, 91, 90, 'News', '3-5 Days', true, true, false, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Professors House', 400.00, 55, 51, 'News', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('The Coaching Magazine', 400.00, 56, 7, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('The Up Coming', 400.00, 65, 72, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, 'tier1', 'standard', true, 10),
('We Rave You', 400.00, 52, 62, 'Music', '1 Week', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Zycrypto', 400.00, 51, 73, 'Crypto', '1 Week', true, true, false, 'GLOBAL', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Luxe Expose', 350.00, 40, 60, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Music News', 350.00, 66, 72, 'Music', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Now Entertainment', 350.00, 62, 35, 'News', '3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10);