-- Add new publications to the database
INSERT INTO publications (name, price, da_score, dr_score, category, tat_days, sponsored, indexed, dofollow_link, location, erotic, health, cbd, crypto, gambling, tier, type, is_active, popularity) VALUES
('Pulse.ng', 700.00, 85, 76, 'News', '2-3 Days', false, true, false, 'NIGERIA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Pulse.sn', 700.00, 35, 33, 'Sports', '2-3 Days', false, true, false, 'SENEGAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Pulse.ug', 700.00, 35, 33, 'News', '2-3 Days', false, true, false, 'UGANDA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('PulseLive.co.ke', 700.00, 56, 61, 'Sports', '2-3 Days', false, true, false, 'KENYA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('PulseSports.co.ke', 700.00, 36, 33, 'Sports', '2-3 Days', false, true, false, 'KENYA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('PulseSports.ug', 700.00, 36, 33, 'Sports', '2-3 Days', false, true, false, 'UGANDA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Retail Insider', 700.00, 57, 74, 'Fashion', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Super Crypto News', 700.00, 33, 41, 'Crypto', '3-5 Days', true, true, false, 'GLOBAL', false, false, false, true, false, 'tier1', 'standard', true, 10),
('The South African', 700.00, 79, 75, 'News', '1 Week', false, true, false, 'SOUTH AFRICA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Digital Journal (Contributor)', 650.00, 87, 87, 'News', '1-3 Days', false, true, true, 'GLOBAL', false, true, true, false, false, 'tier1', 'standard', true, 10),
('Khaleej Times (Press Release)', 650.00, 87, 83, 'News', '1-3 Days', false, true, true, 'UAE', false, true, true, true, false, 'tier1', 'standard', true, 10),
('Billboard Argentina', 600.00, 37, 27, 'Music', '3 Days', false, true, false, 'ARGENTINA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('California Business Journal', 600.00, 40, 70, 'News', '1 Week', false, true, true, 'CALIFORNIA', false, false, false, false, true, 'tier1', 'standard', true, 10),
('CelebMix', 600.00, 63, 64, 'Lifestyle', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Coastal Real Estate Guide', 600.00, 19, 22, 'Real Estate', '1 Week', false, true, true, 'CALIFORNIA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Dancing Astronaut', 600.00, 62, 67, 'Music', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Fashion Week Daily', 600.00, 69, 74, 'Fashion', '3-5 Days', false, true, false, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Finance Digest', 600.00, 64, 71, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Fintech Finance News', 600.00, 39, 73, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Game n Guide', 600.00, 63, 50, 'Gaming', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Global Banking & Finance', 600.00, 81, 79, 'Business', '3-5 Days', false, true, false, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('KPop Starz', 600.00, 82, 62, 'Music', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Laguna Beach Independent', 600.00, 53, 58, 'News', '1 Week', false, true, true, 'CALIFORNIA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Laguna Beach Magazine', 600.00, 27, 39, 'News', '1 Week', false, true, true, 'CALIFORNIA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Latin Post', 600.00, 66, 71, 'News', '1-3 Days', false, true, false, 'LATIN AMERICA', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Latitude 33 Magazine', 600.00, 5, 2, 'Real Estate', '1 Week', false, true, true, 'CALIFORNIA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Lawyer Herald', 600.00, 52, 41, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Money Times', 600.00, 28, 30, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Motor Times', 600.00, 6, 1, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Newport Beach Independent', 600.00, 43, 57, 'News', '1 Week', false, true, true, 'CALIFORNIA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Newport Beach Magazine', 600.00, 32, 38, 'News', '1 Week', false, true, true, 'CALIFORNIA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Outlook India', 600.00, 91, 89, 'News', '1 Week', false, true, false, 'INDIA', false, true, false, true, true, 'tier1', 'standard', true, 10),
('Parents Herald', 600.00, 62, 66, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Science Times', 600.00, 64, 76, 'Tech', '2-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Science World Report', 600.00, 65, 67, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Street Insider', 600.00, 83, 80, 'News', '1-3 Days', true, true, false, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('VC Post', 600.00, 63, 60, 'News', '1-3 Days', false, true, false, 'GLOBAL', false, true, false, true, false, 'tier1', 'standard', true, 10),
('Yahoo News/Finance (AccessWire)', 600.00, 93, 92, 'News', '3-5 Days', true, true, false, 'GLOBAL', false, false, true, false, false, 'tier1', 'standard', true, 10),
('Young Health Magazine', 600.00, 53, 44, 'Lifestyle', '2-3 Days', false, true, true, 'UNITED STATES', false, true, false, true, false, 'tier1', 'standard', true, 10);