-- Continue adding more publications from CSV - Batch 4
-- Using sequential numbering starting from 200 to avoid duplicates
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('bit-rebels-200', 'Bit Rebels', 150, 65, 72, 'Tech', '3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('house-sit-world-201', 'House Sit World', 150, 57, 51, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('highest-networth-magazine-202', 'Highest Networth Magazine', 150, 1, 34, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('san-francisco-tribune-203', 'San Francisco Tribune', 150, 53, 61, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('los-angeles-tribune-204', 'Los Angeles Tribune', 150, 29, 60, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('healthcare-business-today-205', 'Healthcare Business Today', 150, 45, 73, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('kellys-thoughts-on-things-206', 'Kellys Thoughts On Things', 150, 48, 66, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('off-the-mrkt-207', 'Off The MRKT', 150, 33, 58, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ritz-herald-news-208', 'Ritz Herald News', 150, 57, 67, 'News', '1-3 Days', false, true, true, 'GLOBAL', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('political-anthropologist-209', 'Political Anthropologist', 150, 22, 14, 'Political', '1-3 Days', false, true, true, 'EUROPE', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('all-china-review-210', 'All China Review', 150, 30, 22, 'News', '1-3 Days', false, true, true, 'CHINA', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('fairmont-post-211', 'Fairmont Post', 150, 17, 34, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('lincoln-citizen-212', 'Lincoln Citizen', 150, 52, 34, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('belmont-star-213', 'Belmont Star', 150, 52, 35, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('madison-graph-214', 'Madison Graph', 150, 51, 39, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('hudson-weekly-215', 'Hudson Weekly', 150, 54, 49, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('markets-herald-216', 'Markets Herald', 150, 56, 59, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('european-financial-review-217', 'European Financial Review', 150, 46, 62, 'Business', '1-3 Days', false, true, true, 'EUROPE', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('big-time-daily-218', 'Big Time Daily', 150, 54, 64, 'News', '5 Days', false, true, true, 'UNITED STATES', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('psychreg-219', 'Psychreg', 150, 51, 73, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('world-financial-review-220', 'World Financial Review', 150, 49, 73, 'Business', '1-3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('european-business-review-221', 'European Business Review', 150, 56, 79, 'Business', '1-3 Days', false, true, true, 'EUROPE', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('meditech-today-222', 'Meditech Today', 150, 56, 13, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('biz-dispatch-223', 'Biz Dispatch', 150, 55, 20, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('online-world-herald-224', 'Online World Herald', 150, 54, 24, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('international-releases-225', 'International Releases', 150, 54, 25, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('trading-herald-226', 'Trading Herald', 150, 51, 25, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('asset-digest-227', 'Asset Digest', 150, 53, 28, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('wealth-tribune-228', 'Wealth Tribune', 150, 54, 28, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('palm-bay-herald-229', 'Palm Bay Herald', 150, 51, 28, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('economy-standard-230', 'Economy Standard', 150, 54, 29, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('luxury-advisor-231', 'Luxury Advisor', 150, 54, 29, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('blockchain-tribune-232', 'Blockchain Tribune', 150, 54, 30, 'Web 3', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('the-luxe-insider-233', 'The Luxe Insider', 150, 28, 30, 'Luxury', '1-3 Days', false, true, true, 'GLOBAL', false, false, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('startup-observer-234', 'Startup Observer', 150, 57, 31, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('fintech-herald-235', 'Fintech Herald', 150, 55, 36, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('smartech-daily-236', 'Smartech Daily', 150, 56, 45, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('brands-journal-237', 'Brands Journal', 150, 53, 46, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('la-guest-list-238', 'LA Guest List', 150, 40, 46, 'News', '3 Days', false, true, false, 'LOS ANGELES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('companies-digest-239', 'Companies Digest', 150, 56, 48, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0);