-- Add more publications (batch 6) - IDs 540-589
INSERT INTO public.publications (
  external_id, name, type, tier, category, price, tat_days, description, features, 
  website_url, da_score, dr_score, location, dofollow_link, sponsored, indexed,
  erotic, health, cbd, crypto, gambling, popularity, is_active
) VALUES
-- Premium Tech & Business Publications (540-559)
('pub_540', 'VentureBeat', 'premium', 'premium', 'Technology', 2500, '3-5 days', 'Leading technology news publication', '{"Technology News", "Startup Coverage", "Product Reviews"}', 'https://venturebeat.com', 88, 85, 'United States', true, false, true, false, false, false, false, false, 92, true),
('pub_541', 'The Information', 'premium', 'premium', 'Technology', 3500, '2-4 days', 'Premium technology journalism', '{"Tech Industry", "Exclusive Reports", "Analysis"}', 'https://theinformation.com', 85, 82, 'United States', true, false, true, false, false, false, false, false, 88, true),
('pub_542', 'Protocol', 'premium', 'premium', 'Technology', 2800, '3-5 days', 'Enterprise technology news', '{"Enterprise Tech", "Cloud Computing", "AI Coverage"}', 'https://protocol.com', 83, 80, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_543', 'Fast Company', 'premium', 'premium', 'Business', 3200, '4-6 days', 'Innovation and business magazine', '{"Innovation", "Leadership", "Design"}', 'https://fastcompany.com', 89, 86, 'United States', true, false, true, false, false, false, false, false, 91, true),
('pub_544', 'MIT Technology Review', 'premium', 'premium', 'Technology', 4000, '5-7 days', 'Leading technology research publication', '{"Research", "Emerging Tech", "Analysis"}', 'https://technologyreview.com', 91, 88, 'United States', true, false, true, false, false, false, false, false, 94, true),
('pub_545', 'Harvard Business Review', 'premium', 'premium', 'Business', 4500, '7-10 days', 'Premier business publication', '{"Management", "Strategy", "Leadership"}', 'https://hbr.org', 93, 90, 'United States', true, false, true, false, false, false, false, false, 96, true),
('pub_546', 'The Next Web', 'tier1', 'tier1', 'Technology', 1800, '2-4 days', 'European technology news', '{"Startups", "Tech News", "Innovation"}', 'https://thenextweb.com', 81, 78, 'Netherlands', true, false, true, false, false, false, false, false, 83, true),
('pub_547', 'Ars Technica', 'tier1', 'tier1', 'Technology', 2200, '3-5 days', 'In-depth technology coverage', '{"Deep Dives", "Reviews", "Analysis"}', 'https://arstechnica.com', 84, 81, 'United States', true, false, true, false, false, false, false, false, 87, true),
('pub_548', 'Engadget', 'tier1', 'tier1', 'Technology', 1900, '2-3 days', 'Consumer technology news', '{"Gadgets", "Reviews", "Consumer Tech"}', 'https://engadget.com', 82, 79, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_549', 'The Verge', 'tier1', 'tier1', 'Technology', 2400, '3-4 days', 'Technology and culture publication', '{"Tech Culture", "Reviews", "News"}', 'https://theverge.com', 87, 84, 'United States', true, false, true, false, false, false, false, false, 89, true),
('pub_550', 'ZDNet', 'tier1', 'tier1', 'Technology', 1700, '2-4 days', 'Enterprise technology news', '{"Enterprise", "Security", "Cloud"}', 'https://zdnet.com', 80, 77, 'United States', true, false, true, false, false, false, false, false, 82, true),
('pub_551', 'PCMag', 'tier1', 'tier1', 'Technology', 1600, '3-5 days', 'Technology reviews and news', '{"Reviews", "How-to", "Tech News"}', 'https://pcmag.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_552', 'Digital Trends', 'tier2', 'tier2', 'Technology', 1200, '2-4 days', 'Consumer technology coverage', '{"Consumer Tech", "Reviews", "Trends"}', 'https://digitaltrends.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_553', 'CNET', 'tier1', 'tier1', 'Technology', 2000, '3-5 days', 'Technology news and reviews', '{"Reviews", "News", "How-to"}', 'https://cnet.com', 83, 80, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_554', 'Gizmodo', 'tier1', 'tier1', 'Technology', 1800, '2-4 days', 'Technology and science news', '{"Tech News", "Science", "Gadgets"}', 'https://gizmodo.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_555', 'Mashable', 'tier1', 'tier1', 'Technology', 1700, '2-3 days', 'Digital culture and technology', '{"Social Media", "Tech", "Digital Culture"}', 'https://mashable.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),
('pub_556', 'TechRepublic', 'tier2', 'tier2', 'Technology', 1300, '3-5 days', 'IT professional resource', '{"IT News", "Enterprise", "Management"}', 'https://techrepublic.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_557', 'ComputerWorld', 'tier2', 'tier2', 'Technology', 1400, '3-6 days', 'Enterprise IT news', '{"Enterprise IT", "CIO", "Technology"}', 'https://computerworld.com', 77, 74, 'United States', true, false, true, false, false, false, false, false, 79, true),
('pub_558', 'InformationWeek', 'tier2', 'tier2', 'Technology', 1500, '4-6 days', 'Business technology magazine', '{"Business Tech", "Enterprise", "Innovation"}', 'https://informationweek.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_559', 'Network World', 'tier2', 'tier2', 'Technology', 1100, '3-5 days', 'Network technology news', '{"Networking", "Infrastructure", "Security"}', 'https://networkworld.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),

-- Health & Wellness Publications (560-569)
('pub_560', 'Healthline', 'tier1', 'tier1', 'Health', 1800, '3-5 days', 'Leading health information site', '{"Health News", "Medical", "Wellness"}', 'https://healthline.com', 86, 83, 'United States', true, false, true, false, true, false, false, false, 88, true),
('pub_561', 'WebMD', 'tier1', 'tier1', 'Health', 2200, '4-6 days', 'Medical information resource', '{"Medical News", "Health Info", "Symptoms"}', 'https://webmd.com', 89, 86, 'United States', true, false, true, false, true, false, false, false, 91, true),
('pub_562', 'Mayo Clinic News', 'premium', 'premium', 'Health', 3500, '5-7 days', 'Premier medical institution news', '{"Medical Research", "Health News", "Expert Advice"}', 'https://newsnetwork.mayoclinic.org', 92, 89, 'United States', true, false, true, false, true, false, false, false, 94, true),
('pub_563', 'Medical News Today', 'tier2', 'tier2', 'Health', 1200, '2-4 days', 'Medical news publication', '{"Medical News", "Research", "Health Tips"}', 'https://medicalnewstoday.com', 78, 75, 'United Kingdom', true, false, true, false, true, false, false, false, 80, true),
('pub_564', 'Health.com', 'tier2', 'tier2', 'Health', 1400, '3-5 days', 'Health and wellness magazine', '{"Wellness", "Fitness", "Nutrition"}', 'https://health.com', 76, 73, 'United States', true, false, true, false, true, false, false, false, 78, true),
('pub_565', 'Prevention Magazine', 'tier1', 'tier1', 'Health', 1900, '4-6 days', 'Prevention and wellness focus', '{"Prevention", "Wellness", "Healthy Living"}', 'https://prevention.com', 81, 78, 'United States', true, false, true, false, true, false, false, false, 83, true),
('pub_566', 'Everyday Health', 'tier2', 'tier2', 'Health', 1300, '3-5 days', 'Daily health information', '{"Health Tips", "Medical News", "Wellness"}', 'https://everydayhealth.com', 75, 72, 'United States', true, false, true, false, true, false, false, false, 77, true),
('pub_567', 'Verywell Health', 'tier2', 'tier2', 'Health', 1100, '2-4 days', 'Trusted health information', '{"Health Info", "Medical Facts", "Wellness"}', 'https://verywellhealth.com', 74, 71, 'United States', true, false, true, false, true, false, false, false, 76, true),
('pub_568', 'Shape Magazine', 'tier2', 'tier2', 'Health', 1000, '3-5 days', 'Fitness and health magazine', '{"Fitness", "Nutrition", "Wellness"}', 'https://shape.com', 72, 69, 'United States', true, false, true, false, true, false, false, false, 74, true),
('pub_569', 'Mens Health', 'tier1', 'tier1', 'Health', 1700, '3-5 days', 'Mens health and fitness', '{"Fitness", "Health", "Lifestyle"}', 'https://menshealth.com', 79, 76, 'United States', true, false, true, false, true, false, false, false, 81, true),

-- Finance & Investment Publications (570-579)
('pub_570', 'The Motley Fool', 'tier1', 'tier1', 'Finance', 2100, '3-5 days', 'Investment advice and analysis', '{"Investment", "Stock Analysis", "Financial Advice"}', 'https://fool.com', 84, 81, 'United States', true, false, true, false, false, false, false, false, 86, true),
('pub_571', 'Seeking Alpha', 'tier1', 'tier1', 'Finance', 1900, '2-4 days', 'Investment research platform', '{"Investment Research", "Stock Analysis", "Market News"}', 'https://seekingalpha.com', 82, 79, 'United States', true, false, true, false, false, false, false, false, 84, true),
('pub_572', 'MarketWatch', 'tier1', 'tier1', 'Finance', 2300, '2-3 days', 'Financial news and analysis', '{"Market News", "Financial Analysis", "Investment"}', 'https://marketwatch.com', 85, 82, 'United States', true, false, true, false, false, false, false, false, 87, true),
('pub_573', 'Investopedia', 'tier1', 'tier1', 'Finance', 1800, '3-5 days', 'Financial education resource', '{"Financial Education", "Investment", "Market Analysis"}', 'https://investopedia.com', 88, 85, 'United States', true, false, true, false, false, false, false, false, 90, true),
('pub_574', 'TheStreet', 'tier2', 'tier2', 'Finance', 1400, '2-4 days', 'Financial news and analysis', '{"Stock News", "Market Analysis", "Investment"}', 'https://thestreet.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_575', 'Yahoo Finance', 'tier1', 'tier1', 'Finance', 2000, '1-3 days', 'Financial news platform', '{"Market News", "Stock Quotes", "Financial Data"}', 'https://finance.yahoo.com', 91, 88, 'United States', true, false, true, false, false, false, false, false, 93, true),
('pub_576', 'CNN Money', 'tier1', 'tier1', 'Finance', 2400, '2-4 days', 'Financial news from CNN', '{"Business News", "Market Updates", "Economic News"}', 'https://money.cnn.com', 87, 84, 'United States', true, false, true, false, false, false, false, false, 89, true),
('pub_577', 'Bloomberg Personal Finance', 'premium', 'premium', 'Finance', 3200, '3-5 days', 'Personal finance from Bloomberg', '{"Personal Finance", "Investment", "Wealth Management"}', 'https://bloomberg.com/personal-finance', 90, 87, 'United States', true, false, true, false, false, false, false, false, 92, true),
('pub_578', 'Kiplinger', 'tier2', 'tier2', 'Finance', 1300, '4-6 days', 'Personal finance magazine', '{"Personal Finance", "Investment", "Retirement"}', 'https://kiplinger.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_579', 'NerdWallet', 'tier2', 'tier2', 'Finance', 1100, '3-5 days', 'Personal finance guidance', '{"Personal Finance", "Credit", "Banking"}', 'https://nerdwallet.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),

-- Lifestyle & Entertainment (580-589)
('pub_580', 'People Magazine', 'tier1', 'tier1', 'Entertainment', 2200, '3-5 days', 'Celebrity and entertainment news', '{"Celebrity News", "Entertainment", "Lifestyle"}', 'https://people.com', 83, 80, 'United States', true, false, true, false, false, false, false, false, 85, true),
('pub_581', 'Entertainment Tonight', 'tier1', 'tier1', 'Entertainment', 1900, '1-3 days', 'Entertainment news show coverage', '{"Celebrity News", "Entertainment", "TV Shows"}', 'https://etonline.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_582', 'E! News', 'tier2', 'tier2', 'Entertainment', 1500, '1-2 days', 'Entertainment news network', '{"Celebrity News", "Pop Culture", "Fashion"}', 'https://eonline.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_583', 'Us Weekly', 'tier2', 'tier2', 'Entertainment', 1300, '2-4 days', 'Celebrity and lifestyle magazine', '{"Celebrity News", "Lifestyle", "Fashion"}', 'https://usmagazine.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_584', 'InStyle', 'tier2', 'tier2', 'Fashion', 1400, '3-5 days', 'Fashion and beauty magazine', '{"Fashion", "Beauty", "Celebrity Style"}', 'https://instyle.com', 77, 74, 'United States', true, false, true, false, false, false, false, false, 79, true),
('pub_585', 'Marie Claire', 'tier1', 'tier1', 'Fashion', 1800, '4-6 days', 'Fashion and womens magazine', '{"Fashion", "Beauty", "Womens Issues"}', 'https://marieclaire.com', 80, 77, 'United States', true, false, true, false, false, false, false, false, 82, true),
('pub_586', 'Elle', 'tier1', 'tier1', 'Fashion', 2000, '4-6 days', 'Fashion and lifestyle magazine', '{"Fashion", "Beauty", "Culture"}', 'https://elle.com', 82, 79, 'United States', true, false, true, false, false, false, false, false, 84, true),
('pub_587', 'Vogue', 'premium', 'premium', 'Fashion', 4000, '7-10 days', 'Premier fashion magazine', '{"High Fashion", "Luxury", "Culture"}', 'https://vogue.com', 91, 88, 'United States', true, false, true, false, false, false, false, false, 93, true),
('pub_588', 'GQ', 'tier1', 'tier1', 'Fashion', 1900, '4-6 days', 'Mens fashion and lifestyle', '{"Mens Fashion", "Lifestyle", "Culture"}', 'https://gq.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),
('pub_589', 'Cosmopolitan', 'tier1', 'tier1', 'Lifestyle', 1600, '3-5 days', 'Womens lifestyle magazine', '{"Lifestyle", "Relationships", "Career"}', 'https://cosmopolitan.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true);