-- Insert new publications with $97 pricing
INSERT INTO public.publications (
  name, 
  price, 
  category, 
  type, 
  tier, 
  tat_days, 
  status,
  contact_info,
  description,
  features,
  da_score,
  dr_score,
  location,
  dofollow_link,
  sponsored,
  indexed,
  monthly_readers
) VALUES 
  ('Artist Recap', 97.00, 'Entertainment', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Entertainment and artist news publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 45, 42, 'USA', true, false, true, 50000),
  ('AtoZ Times', 97.00, 'News', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'General news and current affairs publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 48, 45, 'USA', true, false, true, 75000),
  ('Womens Reporter', 97.00, 'Lifestyle', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Women-focused news and lifestyle publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 42, 40, 'USA', true, false, true, 60000),
  ('Miami Highlight', 97.00, 'Regional', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Miami regional news and highlights', ARRAY['Article Publication', 'Do-Follow Backlink'], 38, 35, 'Miami, FL', true, false, true, 40000),
  ('Artist Highlight', 97.00, 'Entertainment', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Artist and entertainment industry coverage', ARRAY['Article Publication', 'Do-Follow Backlink'], 44, 41, 'USA', true, false, true, 55000),
  ('Texas Recap', 97.00, 'Regional', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Texas state news and business coverage', ARRAY['Article Publication', 'Do-Follow Backlink'], 46, 43, 'Texas, USA', true, false, true, 80000),
  ('The Leader Report', 97.00, 'Business', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Leadership and business insights publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 50, 47, 'USA', true, false, true, 65000),
  ('Golden State Review', 97.00, 'Regional', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'California state business and news review', ARRAY['Article Publication', 'Do-Follow Backlink'], 49, 46, 'California, USA', true, false, true, 85000),
  ('MensReporter', 97.00, 'Lifestyle', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Men-focused news and lifestyle publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 43, 40, 'USA', true, false, true, 58000),
  ('Best in Houses', 97.00, 'Real Estate', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Real estate and housing market publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 41, 38, 'USA', true, false, true, 45000),
  ('Juris Review', 97.00, 'Legal', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Legal industry news and analysis', ARRAY['Article Publication', 'Do-Follow Backlink'], 47, 44, 'USA', true, false, true, 35000),
  ('Todays Read', 97.00, 'News', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Daily news and current events publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 45, 42, 'USA', true, false, true, 70000),
  ('Celeb Digest', 97.00, 'Entertainment', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Celebrity news and entertainment digest', ARRAY['Article Publication', 'Do-Follow Backlink'], 46, 43, 'USA', true, false, true, 90000),
  ('Primetime Press', 97.00, 'Entertainment', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Primetime entertainment and media coverage', ARRAY['Article Publication', 'Do-Follow Backlink'], 44, 41, 'USA', true, false, true, 65000),
  ('Mens Newspaper', 97.00, 'Lifestyle', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Men-focused news and lifestyle newspaper', ARRAY['Article Publication', 'Do-Follow Backlink'], 42, 39, 'USA', true, false, true, 52000),
  ('Rent Magazine', 97.00, 'Real Estate', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Rental market and property management magazine', ARRAY['Article Publication', 'Do-Follow Backlink'], 40, 37, 'USA', true, false, true, 38000),
  ('Empire State Review', 97.00, 'Regional', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'New York state business and news review', ARRAY['Article Publication', 'Do-Follow Backlink'], 51, 48, 'New York, USA', true, false, true, 95000),
  ('Top Listings', 97.00, 'Business', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Business listings and company features', ARRAY['Article Publication', 'Do-Follow Backlink'], 43, 40, 'USA', true, false, true, 42000),
  ('Good Morning US', 97.00, 'News', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Morning news and current affairs publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 47, 44, 'USA', true, false, true, 78000),
  ('Biz Recap', 97.00, 'Business', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Business news and market recap publication', ARRAY['Article Publication', 'Do-Follow Backlink'], 48, 45, 'USA', true, false, true, 68000),
  ('Womens Insider', 97.00, 'Lifestyle', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Women-focused insider news and trends', ARRAY['Article Publication', 'Do-Follow Backlink'], 44, 41, 'USA', true, false, true, 72000),
  ('NY Review', 97.00, 'Regional', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'New York regional news and business review', ARRAY['Article Publication', 'Do-Follow Backlink'], 50, 47, 'New York, USA', true, false, true, 88000),
  ('Biz Weekly', 97.00, 'Business', 'standard', 'premium', '1-3 Days', 'active', '[Contact Available After Purchase]', 'Weekly business news and analysis', ARRAY['Article Publication', 'Do-Follow Backlink'], 46, 43, 'USA', true, false, true, 62000);