-- Continue adding more publications from CSV - Batch 5
-- Adding more premium and major publications
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('business-express-240', 'Business Express', 150, 62, 48, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('financial-tech-times-241', 'Financial Tech Times', 150, 56, 50, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('entrepreneur-tribune-242', 'Entrepreneur Tribune', 150, 52, 52, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('transit-tomorrow-243', 'Transit Tomorrow', 150, 57, 57, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('technology-dispatch-244', 'Technology Dispatch', 150, 54, 59, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('chiang-rai-times-245', 'Chiang Rai Times', 150, 80, 70, 'News', '3-5 Days', false, true, false, 'GLOBAL', false, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('high-net-worth-magazine-246', 'High Net Worth Magazine', 150, 2, 61, 'Business', '1 Day', false, true, true, 'UNITED STATES', false, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('gadgets-gaadi-247', 'Gadgets Gaadi', 150, 21, 37, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('kansas-press-248', 'Kansas Press', 150, 21, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('lux-ent-249', 'Lux & Ent', 150, 13, 8, 'Entertainment', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('tennessee-independent-250', 'Tennessee Independent', 150, 42, 44, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('jane-resture-251', 'Jane Resture', 150, 45, 45, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('scotlands-enchanting-kingdom-252', 'Scotlands Enchanting Kingdom', 150, 34, 51, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('commercial-architecture-magazine-253', 'Commercial Architecture Magazine', 150, 31, 46, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('bug-bog-254', 'Bug Bog', 150, 52, 50, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('urban-kenyans-255', 'Urban Kenyans', 150, 30, 53, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('ww-journals-256', 'WW Journals', 150, 51, 59, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('mississippi-independent-257', 'Mississippi Independent', 150, 28, 45, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('grimball-jewelers-258', 'GrimballJewelers.com', 150, 39, 49, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('novabach-259', 'Novabach.com', 150, 24, 34, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('cannabiss-blog-260', 'Cannabiss Blog', 150, 58, 51, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('pure-net-wealth-261', 'Pure Net Wealth', 150, 26, 48, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('law-news-network-262', 'Law News Network', 150, 35, 42, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('the-hook-web-263', 'The Hook Web', 150, 49, 53, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('multiplayerpiano-264', 'Multiplayerpiano.com', 150, 42, 52, 'Music', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('san-francisco-post-265', 'San Francisco Post', 150, 56, 52, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('now-entertainment-266', 'Now Entertainment', 175, 62, 35, 'News', '3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('music-news-267', 'Music News', 175, 66, 72, 'Music', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('luxe-expose-268', 'Luxe Expose', 175, 40, 60, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('redx-magazine-269', 'RedX Magazine', 199, 53, 51, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('the-tribune-india-270', 'The Tribune India', 200, 87, 81, 'News', '1-3 Days', true, true, false, 'INDIA', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('neon-music-271', 'Neon Music', 200, 63, 58, 'Music', '3-5 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('professors-house-272', 'Professors House', 200, 55, 51, 'News', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('anglotopia-273', 'Anglotopia', 200, 62, 56, 'News', '3 Days', false, true, true, 'ILLINOIS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('zycrypto-274', 'Zycrypto', 200, 51, 73, 'Crypto', '1 Week', true, true, false, 'GLOBAL', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('magnetic-mag-275', 'Magnetic Mag', 200, 75, 70, 'Music', '3 Days', true, true, false, 'GLOBAL', false, false, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('1883-magazine-276', '1883 Magazine', 200, 53, 62, 'News', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('fine-homes-and-living-277', 'Fine Homes and Living', 200, 44, 63, 'Real Estate', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('home-town-station-278', 'Home Town Station', 200, 66, 75, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-up-coming-279', 'The Up Coming', 200, 65, 72, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0);