-- Continue adding more publications from the CSV file
-- Batch 2: Publications 41-100
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('lit-magazine-041', 'LIT. Magazine', 100, 37, 27, 'News', '3 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('momma-cuisine-042', 'Momma Cuisine', 100, 34, 37, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('mom-blog-society-043', 'Mom Blog Society', 100, 37, 63, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('gisuser-044', 'GISuser', 100, 50, 68, 'Tech', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-bragging-mommy-045', 'The Bragging Mommy', 100, 37, 51, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('curious-mind-magazine-046', 'Curious Mind Magazine', 100, 64, 56, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, true, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('news-today-047', 'News Today', 100, 66, 31, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('fox-interviewer-048', 'Fox Interviewer', 100, 58, 57, 'News', '1 Days', false, true, false, 'GLOBAL', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('the-sustainable-post-049', 'The Sustainable Post', 100, 62, 1, 'News', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-texas-developer-050', 'The Texas Developer', 100, 57, 52, 'News', '3 Days', false, true, true, 'TEXAS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('metapress-051', 'MetaPress', 100, 77, 81, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('dubai-weekly-052', 'Dubai Weekly', 100, 62, 1, 'News', '3 Days', false, true, true, 'MIDDLE EAST', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-influence-journal-053', 'The Influence Journal', 100, 60, 5, 'News', '3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('elite-music-news-054', 'Elite Music News', 100, 51, 17, 'Music', '1-3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('west-hollywood-weekly-055', 'West Hollywood Weekly', 100, 56, 19, 'Lifestyle', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('huff-mag-056', 'Huff Mag', 100, 62, 33, 'News', '1 Day', false, true, false, 'GLOBAL', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('the-beverly-weekly-057', 'The Beverly Weekly', 100, 62, 38, 'Lifestyle', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('elite-property-news-058', 'Elite Property News', 100, 60, 42, 'Real Estate', '3-5 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-influential-059', 'The Influential', 100, 62, 42, 'Lifestyle', '3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('elite-luxury-news-060', 'Elite Luxury News', 100, 62, 42, 'Luxury', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('broke-chic-061', 'Broke & Chic', 100, 35, 45, 'News', '1-3 Days', false, true, true, 'GLOBAL', false, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('muzique-magazine-062', 'Muzique Magazine', 100, 55, 53, 'Music', '1-3 Days', false, true, false, 'GLOBAL', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('luxury-miami-magazine-063', 'Luxury Miami Magazine', 100, 1, 35, 'Luxury', '2-3 Days', false, true, false, 'FLORIDA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ceo-official-mag-064', 'CEO Official Mag', 100, 1, 35, 'Business', '2-3 Days', false, true, false, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('health-living-house-065', 'Health Living House', 125, 37, 19, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('providr-066', 'Providr', 125, 71, 45, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-power-of-silence-067', 'The Power of Silence', 125, 46, 42, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('rosepedia-068', 'Rosepedia', 125, 25, 35, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('diet-of-life-069', 'Diet of Life', 125, 46, 38, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('london-webcam-070', 'London Webcam', 125, 20, 47, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('health-mind-magazine-071', 'Health Mind Magazine', 125, 9, 76, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('hangry-pants-072', 'Hangry Pants', 125, 25, 35, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('new-jersey-independent-073', 'New Jersey Independent', 125, 16, 37, 'Lifestyle', '3-5 Days', false, true, true, 'NEW JERSEY', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('entertainment-post-074', 'Entertainment Post', 125, 55, 46, 'Entertainment', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('economic-insider-075', 'Economic Insider', 125, 55, 50, 'Business/News', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('texas-today-076', 'Texas Today', 125, 57, 58, 'News', '2-4 Days', true, true, true, 'TEXAS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('networth-us-077', 'Networth.us', 125, 56, 26, 'Business', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('us-business-news-078', 'US Business News', 125, 57, 52, 'Lifestyle', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('real-estate-today-079', 'Real Estate Today', 125, 18, 43, 'Real Estate', '2-4 Days', true, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('miami-wire-080', 'Miami Wire', 125, 17, 44, 'News', '2-4 Days', true, true, true, 'MIAMI', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('famous-times-081', 'Famous Times', 125, 60, 47, 'Entertainment', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0);