-- Add remaining $300 publications
INSERT INTO publications (name, price, da_score, dr_score, category, tat_days, sponsored, indexed, dofollow_link, location, erotic, health, cbd, crypto, gambling, tier, type, is_active, popularity) VALUES
('Kellys Thoughts On Things', 300.00, 48, 66, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, 'tier1', 'standard', true, 10),
('LA Guest List', 300.00, 40, 46, 'News', '3 Days', false, true, false, 'LOS ANGELES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Law News Network', 300.00, 35, 42, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Lincoln Citizen', 300.00, 52, 34, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Los Angeles Tribune', 300.00, 29, 60, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Lux & Ent', 300.00, 13, 8, 'Entertainment', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Luxury Advisor', 300.00, 54, 29, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Madison Graph', 300.00, 51, 39, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Markets Herald', 300.00, 56, 59, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Marx-Communications.com', 300.00, 39, 52, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Meditech Today', 300.00, 56, 13, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Mississippi Independent', 300.00, 28, 45, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Multiplayerpiano.com', 300.00, 42, 52, 'Music', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('My Face Hunter', 300.00, 72, 61, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('New York Street Food', 300.00, 66, 45, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Nohoarts District', 300.00, 47, 64, 'News', '2-3 Days', false, true, true, 'UNITED STATES', true, true, true, true, true, 'tier1', 'standard', true, 10),
('Novabach.com', 300.00, 24, 34, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Off The MRKT', 300.00, 33, 58, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Oh My Dish', 300.00, 42, 52, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Oh My Dish (Netherlands)', 300.00, 29, 28, 'Lifestyle', '3-5 Days', false, true, true, 'NETHERLANDS', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Online World Herald', 300.00, 54, 24, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Our Kid Things', 300.00, 46, 49, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Palm Bay Herald', 300.00, 51, 28, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Political Anthropologist', 300.00, 22, 14, 'Political', '1-3 Days', false, true, true, 'EUROPE', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Psychreg', 300.00, 51, 73, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', true, true, true, true, true, 'tier1', 'standard', true, 10),
('Pure Net Wealth', 300.00, 26, 48, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Ritz Herald News', 300.00, 57, 67, 'News', '1-3 Days', false, true, true, 'GLOBAL', false, true, true, true, true, 'tier1', 'standard', true, 10),
('San Francisco Tribune', 300.00, 53, 61, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, true, true, true, false, 'tier1', 'standard', true, 10),
('Scotlands Enchanting Kingdom', 300.00, 34, 51, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Shibley Smiles', 300.00, 46, 54, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10);