-- Continue adding more publications from CSV - Batch 7
-- Adding more tech, lifestyle, and business publications
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('gizmodo-400', 'Gizmodo', 350, 81, 80, 'Tech', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('ars-technica-401', 'Ars Technica', 400, 84, 83, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('mashable-402', 'Mashable', 350, 82, 81, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('venturebeat-403', 'VentureBeat', 400, 86, 85, 'Tech', '2-4 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('recode-404', 'Recode', 350, 83, 82, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('cnet-405', 'CNET', 300, 80, 79, 'Tech', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('zdnet-406', 'ZDNet', 300, 79, 78, 'Tech', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 81),
('pcmag-407', 'PCMag', 250, 78, 77, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('computerworld-408', 'Computerworld', 275, 76, 75, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('infoworld-409', 'InfoWorld', 250, 74, 73, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('network-world-410', 'Network World', 225, 72, 71, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('digital-trends-411', 'Digital Trends', 275, 75, 74, 'Tech', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('tom-hardware-412', 'Toms Hardware', 250, 73, 72, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('anandtech-413', 'AnandTech', 300, 77, 76, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('tech-radar-414', 'TechRadar', 250, 74, 73, 'Tech', '2-3 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-register-415', 'The Register', 225, 71, 70, 'Tech', '1-2 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('silicon-valley-business-journal-416', 'Silicon Valley Business Journal', 300, 68, 67, 'Business', '1 Week', false, true, true, 'CALIFORNIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('crunchbase-news-417', 'Crunchbase News', 250, 70, 69, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('startup-grind-418', 'Startup Grind', 200, 65, 64, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('product-hunt-419', 'Product Hunt', 175, 72, 71, 'Tech', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('hacker-news-420', 'Hacker News', 150, 85, 84, 'Tech', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('reddit-421', 'Reddit', 200, 91, 90, 'News', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 92),
('medium-tech-422', 'Medium (Tech)', 125, 95, 94, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 95),
('dev-to-423', 'Dev.to', 100, 78, 77, 'Tech', '1-2 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('github-blog-424', 'GitHub Blog', 150, 89, 88, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('stack-overflow-blog-425', 'Stack Overflow Blog', 175, 87, 86, 'Tech', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('adobe-blog-426', 'Adobe Blog', 200, 84, 83, 'Tech', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('microsoft-news-427', 'Microsoft News', 250, 88, 87, 'Tech', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('google-blog-428', 'Google Blog', 300, 92, 91, 'Tech', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('apple-newsroom-429', 'Apple Newsroom', 400, 90, 89, 'Tech', '1-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('facebook-newsroom-430', 'Facebook Newsroom', 350, 86, 85, 'Tech', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('twitter-blog-431', 'Twitter Blog', 300, 84, 83, 'Tech', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('linkedin-news-432', 'LinkedIn News', 275, 89, 88, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('salesforce-blog-433', 'Salesforce Blog', 250, 83, 82, 'Business', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('hubspot-blog-434', 'HubSpot Blog', 200, 81, 80, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('shopify-blog-435', 'Shopify Blog', 225, 82, 81, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('stripe-blog-436', 'Stripe Blog', 250, 85, 84, 'Business', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('paypal-newsroom-437', 'PayPal Newsroom', 225, 83, 82, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('square-news-438', 'Square News', 200, 80, 79, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('uber-newsroom-439', 'Uber Newsroom', 275, 84, 83, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86);