-- Final major batch - Adding diverse international and specialized publications
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
-- International Premium Publications
('le-monde-600', 'Le Monde', 550, 92, 91, 'News', '1 Week', false, true, true, 'FRANCE', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('der-spiegel-601', 'Der Spiegel', 500, 90, 89, 'News', '1 Week', false, true, true, 'GERMANY', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 92),
('la-repubblica-602', 'La Repubblica', 450, 88, 87, 'News', '3-5 Days', false, true, true, 'ITALY', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('el-pais-603', 'El Pais', 400, 86, 85, 'News', '3-5 Days', false, true, true, 'SPAIN', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('nikkei-asian-review-604', 'Nikkei Asian Review', 350, 84, 83, 'Business', '1 Week', false, true, true, 'JAPAN', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('south-china-morning-post-605', 'South China Morning Post', 300, 82, 81, 'News', '3-5 Days', false, true, true, 'HONG KONG', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('times-of-india-606', 'Times of India', 250, 80, 79, 'News', '2-3 Days', false, true, true, 'INDIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('australian-financial-review-607', 'Australian Financial Review', 400, 85, 84, 'Business', '1 Week', false, true, true, 'AUSTRALIA', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('globe-and-mail-608', 'Globe and Mail', 350, 83, 82, 'News', '3-5 Days', false, true, true, 'CANADA', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('straits-times-609', 'Straits Times', 275, 81, 80, 'News', '2-3 Days', false, true, true, 'SINGAPORE', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),

-- Specialized Industry Publications
('automotive-news-610', 'Automotive News', 300, 75, 74, 'Automotive', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('aviation-week-611', 'Aviation Week', 350, 78, 77, 'Aviation', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('oil-gas-journal-612', 'Oil & Gas Journal', 400, 76, 75, 'Energy', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('power-magazine-613', 'Power Magazine', 275, 73, 72, 'Energy', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('chemical-engineering-614', 'Chemical Engineering', 300, 74, 73, 'Science', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('nature-615', 'Nature', 600, 91, 90, 'Science', '4-6 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('science-magazine-616', 'Science Magazine', 550, 89, 88, 'Science', '3-5 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('new-england-journal-medicine-617', 'New England Journal of Medicine', 500, 87, 86, 'Medical', '4-8 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('jama-618', 'JAMA', 450, 85, 84, 'Medical', '3-6 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('lancet-619', 'The Lancet', 475, 86, 85, 'Medical', '4-8 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),

-- Regional US Publications
('chicago-tribune-620', 'Chicago Tribune', 275, 79, 78, 'News', '3-5 Days', false, true, true, 'ILLINOIS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('los-angeles-times-621', 'Los Angeles Times', 350, 83, 82, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('boston-globe-622', 'Boston Globe', 300, 81, 80, 'News', '3-5 Days', false, true, true, 'MASSACHUSETTS', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('seattle-times-623', 'Seattle Times', 250, 78, 77, 'News', '2-3 Days', false, true, true, 'WASHINGTON', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('miami-herald-624', 'Miami Herald', 225, 76, 75, 'News', '2-3 Days', false, true, true, 'FLORIDA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('denver-post-625', 'Denver Post', 200, 74, 73, 'News', '2-3 Days', false, true, true, 'COLORADO', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('atlanta-journal-constitution-626', 'Atlanta Journal Constitution', 225, 77, 76, 'News', '2-3 Days', false, true, true, 'GEORGIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('dallas-morning-news-627', 'Dallas Morning News', 250, 78, 77, 'News', '3-5 Days', false, true, true, 'TEXAS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('philadelphia-inquirer-628', 'Philadelphia Inquirer', 275, 79, 78, 'News', '3-5 Days', false, true, true, 'PENNSYLVANIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('san-francisco-chronicle-629', 'San Francisco Chronicle', 300, 81, 80, 'News', '3-5 Days', false, true, true, 'CALIFORNIA', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),

-- Digital Native Publications
('buzzfeed-news-630', 'BuzzFeed News', 200, 77, 76, 'News', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('huffpost-631', 'HuffPost', 250, 80, 79, 'News', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('vox-632', 'Vox', 275, 82, 81, 'News', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('axios-633', 'Axios', 300, 83, 82, 'News', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('politico-634', 'Politico', 350, 85, 84, 'Politics', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('the-hill-635', 'The Hill', 275, 81, 80, 'Politics', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('daily-beast-636', 'Daily Beast', 225, 78, 77, 'News', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('slate-637', 'Slate', 200, 76, 75, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('salon-638', 'Salon', 175, 74, 73, 'News', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('motherjones-639', 'Mother Jones', 250, 79, 78, 'Politics', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0);