-- Add final batch of $300 publications
INSERT INTO publications (name, price, da_score, dr_score, category, tat_days, sponsored, indexed, dofollow_link, location, erotic, health, cbd, crypto, gambling, tier, type, is_active, popularity) VALUES
('All China Review', 300.00, 30, 22, 'News', '1-3 Days', false, true, true, 'CHINA', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Asset Digest', 300.00, 53, 28, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Belmont Star', 300.00, 52, 35, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Big Time Daily', 300.00, 54, 64, 'News', '5 Days', false, true, true, 'UNITED STATES', true, true, true, true, true, 'tier1', 'standard', true, 10),
('Bit Rebels', 300.00, 65, 72, 'Tech', '3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Biz Dispatch', 300.00, 55, 20, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Blockchain Tribune', 300.00, 54, 30, 'Web 3', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Brands Journal', 300.00, 53, 46, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Bug Bog', 300.00, 52, 50, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Business Express', 300.00, 62, 48, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Cannabiss Blog', 300.00, 58, 51, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Chiang Rai Times', 300.00, 80, 70, 'News', '3-5 Days', false, true, false, 'GLOBAL', false, true, true, true, false, 'tier1', 'standard', true, 10),
('Commercial Architecture Magazine', 300.00, 31, 46, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Companies Digest', 300.00, 56, 48, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Cultr Magazine', 300.00, 34, 48, 'Music', '1-2 Days', false, true, true, 'GLOBAL', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Daily RX', 300.00, 49, 54, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, true, false, false, 'tier1', 'standard', true, 10),
('Design By Sully', 300.00, 56, 55, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Economy Standard', 300.00, 54, 29, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Entrepreneur Tribune', 300.00, 52, 52, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('European Business Review', 300.00, 56, 79, 'Business', '1-3 Days', false, true, true, 'EUROPE', false, false, false, false, false, 'tier1', 'standard', true, 10),
('European Financial Review', 300.00, 46, 62, 'Business', '1-3 Days', false, true, true, 'EUROPE', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Fairmont Post', 300.00, 17, 34, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Financial Tech Times', 300.00, 56, 50, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Fintech Herald', 300.00, 55, 36, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Gadgets Gaadi', 300.00, 21, 37, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Get World Beauty', 300.00, 55, 49, 'Fashion', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Girl Cooks World', 300.00, 49, 53, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, 'tier1', 'standard', true, 10),
('GrimballJewelers.com', 300.00, 39, 49, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Healthcare Business Today', 300.00, 45, 73, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, 'tier1', 'standard', true, 10),
('High Net Worth Magazine', 300.00, 2, 61, 'Business', '1 Day', false, true, true, 'UNITED STATES', false, true, true, true, false, 'tier1', 'standard', true, 10),
('Highest Networth Magazine', 300.00, 1, 34, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Homes Creative', 300.00, 52, 35, 'Real Estate', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('House Sit World', 300.00, 57, 51, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, 'tier1', 'standard', true, 10),
('Hudson Weekly', 300.00, 54, 49, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, true, true, true, 'tier1', 'standard', true, 10),
('Hype Magazine', 300.00, 64, 72, 'Lifestyle', '1 Week', false, true, true, 'GLOBAL', false, true, true, true, false, 'tier1', 'standard', true, 10),
('Innov8tiv', 300.00, 48, 62, 'Tech', '3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('International Releases', 300.00, 54, 25, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, 'tier1', 'standard', true, 10),
('Jane Resture', 300.00, 45, 45, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10),
('Kansas Press', 300.00, 21, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', true, true, true, true, false, 'tier1', 'standard', true, 10);