-- Continue adding more publications from CSV - Batch 6
-- Starting from 300 to avoid duplicates
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('i-love-south-africa-300', 'I Love South Africa', 200, 18, 56, 'News', '3-5 Days', false, true, true, 'AFRICA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('mom-the-mag-301', 'Mom The Mag', 200, 56, 35, 'Lifestyle', '1-3 Days', false, true, false, 'UNITED STATES', false, true, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('edm-sauce-302', 'EDM Sauce', 200, 76, 60, 'Music', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 80),
('we-rave-you-303', 'We Rave You', 200, 52, 62, 'Music', '1 Week', false, true, false, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('deadline-new-304', 'Deadline New', 200, 74, 68, 'News', '3 Days', false, true, false, 'GLOBAL', false, true, true, true, true, true, 'premium', 'premium', '', '{}', 75),
('allhiphop-305', 'AllHipHop', 200, 73, 73, 'Music', '1 Week', false, true, false, 'GLOBAL', false, true, true, true, false, true, 'premium', 'premium', '', '{}', 78),
('art-daily-306', 'Art Daily', 200, 65, 79, 'Entertainment', '1-3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 70),
('patch-com-307', 'Patch.com', 200, 91, 90, 'News', '3-5 Days', true, true, false, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('good-men-project-308', 'Good Men Project', 200, 82, 79, 'News', '1 Week', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('ny-tech-media-309', 'NY Tech Media', 200, 34, 34, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('coin-review-news-310', 'Coin Review News', 250, 29, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('startupbooted-311', 'StartUpBooted.com', 250, 55, 67, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('percentagecalculatorshub-312', 'PercentageCalculatorsHub.com', 250, 53, 67, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('snapchatplanet-313', 'SnapchatPlanet.com', 250, 43, 64, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('growthnavigate-314', 'GrowthNavigate.com', 250, 50, 61, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ib-times-ap-315', 'IB Times (AP)', 250, 73, 72, 'Business', '1 Week', false, true, false, 'ASIA PACIFIC', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 75),
('cultr-magazine-316', 'Cultr Magazine', 250, 34, 48, 'Music', '1 Week', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('benzinga-317', 'Benzinga', 300, 82, 85, 'Business', '1-2 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('yahoo-finance-318', 'Yahoo Finance', 400, 93, 92, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 95),
('marketwatch-319', 'MarketWatch', 350, 89, 88, 'Business', '2-4 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('techcrunch-320', 'TechCrunch', 500, 92, 91, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 95),
('entrepreneur-magazine-321', 'Entrepreneur Magazine', 400, 88, 87, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 92),
('inc-magazine-322', 'Inc. Magazine', 450, 90, 89, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('fast-company-323', 'Fast Company', 400, 87, 86, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('business-insider-324', 'Business Insider', 500, 90, 89, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('reuters-325', 'Reuters', 600, 96, 95, 'News', '1-2 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 98),
('bloomberg-326', 'Bloomberg', 700, 97, 96, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 99),
('the-new-york-times-327', 'The New York Times', 800, 98, 97, 'News', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 100),
('washington-post-328', 'Washington Post', 700, 96, 95, 'News', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 98),
('the-guardian-329', 'The Guardian', 600, 94, 93, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 96),
('bbc-news-330', 'BBC News', 650, 95, 94, 'News', '1 Week', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 97),
('usa-today-331', 'USA Today', 500, 88, 87, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('time-magazine-332', 'Time Magazine', 600, 92, 91, 'News', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('newsweek-333', 'Newsweek', 500, 86, 85, 'News', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('the-economist-334', 'The Economist', 750, 94, 93, 'Business', '2-3 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 96),
('financial-times-335', 'Financial Times', 700, 93, 92, 'Business', '1 Week', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 95),
('harvard-business-review-336', 'Harvard Business Review', 800, 91, 90, 'Business', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('wired-magazine-337', 'Wired Magazine', 550, 89, 88, 'Tech', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('the-verge-338', 'The Verge', 450, 85, 84, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('engadget-339', 'Engadget', 400, 83, 82, 'Tech', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85);