-- Continue adding more high-value publications from the CSV file
-- Adding major publications like Forbes, CNN, NBC, AP, Wall Street Times, etc.
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('forbes-082', 'Forbes', 500, 95, 95, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 100),
('cnn-083', 'CNN', 450, 95, 94, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 98),
('nbc-news-084', 'NBC News', 400, 93, 92, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 95),
('associated-press-085', 'Associated Press', 350, 92, 91, 'News', '2-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('wall-street-journal-086', 'Wall Street Journal', 600, 94, 93, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 97),
('us-insider-087', 'US Insider', 125, 57, 52, 'News', '2-4 Days', true, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ny-wire-088', 'NY Wire', 125, 56, 54, 'News', '2-4 Days', true, true, true, 'NEW YORK', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('influencer-daily-089', 'Influencer Daily', 125, 58, 54, 'News', '2-4 Days', true, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('entertainment-monthly-news-090', 'Entertainment Monthly News', 125, 56, 54, 'News', '2-4 Days', true, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('atlanta-wire-091', 'Atlanta Wire', 125, 11, 55, 'News', '2-4 Days', true, true, true, 'GEORGIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('artist-weekly-092', 'Artist Weekly', 125, 55, 55, 'Music', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('chicago-journal-093', 'Chicago Journal', 125, 52, 55, 'News', '2-4 Days', true, true, true, 'ILLINOIS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('us-reporter-094', 'US Reporter', 125, 56, 56, 'News', '2-4 Days', true, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('portland-news-095', 'Portland News', 125, 57, 57, 'News', '2-4 Days', true, true, true, 'OREGON', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('music-observer-096', 'Music Observer', 125, 60, 60, 'News', '2-4 Days', true, true, true, 'GLOBAL', false, false, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('voyage-new-york-097', 'Voyage New York', 125, 56, 61, 'News', '2-4 Days', true, true, true, 'NEW YORK', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ceo-weekly-098', 'CEO Weekly', 125, 28, 64, 'News', '2-4 Days', true, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('la-wire-099', 'LA Wire', 125, 57, 65, 'News', '2-4 Days', true, true, true, 'LOS ANGELES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ny-weekly-100', 'NY Weekly', 125, 57, 74, 'News', '2-4 Days', true, true, true, 'NEW YORK', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('celebrity-news-101', 'Celebrity News', 125, 53, 49, 'Entertainment', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('world-reporter-102', 'World Reporter', 125, 56, 53, 'News', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('blk-news-103', 'BLK News', 125, 52, 52, 'News', '2-4 Days', true, true, true, 'NEW YORK', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('market-daily-104', 'Market Daily', 125, 59, 46, 'Business', '2-4 Days', true, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('wall-street-times-105', 'Wall Street Times', 125, 54, 51, 'Business', '2-4 Days', true, true, true, 'NEW YORK', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('womens-journal-106', 'Womens Journal', 125, 55, 55, 'Lifestyle', '2-4 Days', true, true, false, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('kivo-daily-107', 'Kivo Daily', 125, 37, 63, 'News', '1-2 Days', false, true, true, 'GLOBAL', false, false, false, true, true, true, 'standard', 'standard', '', '{}', 0),
('load2learn-108', 'Load2Learn', 125, 40, 0, 'News', '1-3 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('scotland-b2b-109', 'Scotland B2B', 125, 33, 42, 'News', '2-3 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('infopool-110', 'Infopool', 125, 60, 43, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, true, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('the-naptime-reviewer-111', 'The Naptime Reviewer', 125, 35, 50, 'News', '2-3 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-dedicated-house-112', 'The Dedicated House', 125, 33, 53, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('flare-magazine-113', 'Flare Magazine', 125, 37, 36, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED KINGDOM', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('stephi-lareine-114', 'Stephi Lareine', 125, 60, 41, 'Lifestyle/News', '3-5 Days', false, true, true, 'UNITED KINGDOM', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('infinity-else-115', 'Infinity Else', 125, 35, 39, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('luxury-travel-magazine-116', 'Luxury Travel Magazine', 125, 53, 71, 'Lifestyle', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('nano-biz-tech-117', 'Nano Biz Tech', 125, 59, 46, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('style-beauty-health-118', 'Style Beauty Health', 125, 62, 44, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('holly-health-fitness-119', 'Holly Health Fitness', 125, 58, 42, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-reddit-blog-120', 'The Reddit Blog', 125, 57, 31, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('digital-fitness-world-121', 'Digital Fitness World', 125, 56, 38, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0);