-- Add more publications (batch 8) - IDs 650-699
INSERT INTO public.publications (
  external_id, name, type, tier, category, price, tat_days, description, features, 
  website_url, da_score, dr_score, location, dofollow_link, sponsored, indexed,
  erotic, health, cbd, crypto, gambling, popularity, is_active
) VALUES
-- Science & Research Publications (650-659)
('pub_650', 'Scientific American', 'premium', 'premium', 'Science', 3500, '5-7 days', 'Leading science magazine', '{"Science News", "Research", "Innovation"}', 'https://scientificamerican.com', 89, 86, 'United States', true, false, true, false, false, false, false, false, 91, true),
('pub_651', 'Popular Science', 'tier1', 'tier1', 'Science', 1800, '3-5 days', 'Popular science magazine', '{"Science", "Technology", "Innovation"}', 'https://popsci.com', 81, 78, 'United States', true, false, true, false, false, false, false, false, 83, true),
('pub_652', 'Nature News', 'premium', 'premium', 'Science', 4200, '7-10 days', 'Premier scientific journal', '{"Scientific Research", "Peer Review", "Academic"}', 'https://nature.com/news', 94, 91, 'United Kingdom', true, false, true, false, false, false, false, false, 96, true),
('pub_653', 'Science Magazine', 'premium', 'premium', 'Science', 4000, '6-9 days', 'Leading scientific publication', '{"Research", "Scientific Studies", "Academic"}', 'https://science.org', 93, 90, 'United States', true, false, true, false, false, false, false, false, 95, true),
('pub_654', 'Discover Magazine', 'tier1', 'tier1', 'Science', 1700, '3-5 days', 'Science discovery magazine', '{"Science Discovery", "Research", "Innovation"}', 'https://discovermagazine.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_655', 'New Scientist', 'tier1', 'tier1', 'Science', 2000, '4-6 days', 'Science and technology weekly', '{"Science News", "Technology", "Research"}', 'https://newscientist.com', 84, 81, 'United Kingdom', true, false, true, false, false, false, false, false, 86, true),
('pub_656', 'Smithsonian Magazine', 'tier1', 'tier1', 'Science', 2100, '4-6 days', 'Science, history, and culture', '{"Science", "History", "Culture"}', 'https://smithsonianmag.com', 86, 83, 'United States', true, false, true, false, false, false, false, false, 88, true),
('pub_657', 'National Geographic', 'premium', 'premium', 'Science', 3800, '5-8 days', 'Nature and science exploration', '{"Nature", "Science", "Exploration"}', 'https://nationalgeographic.com', 92, 89, 'United States', true, false, true, false, false, false, false, false, 94, true),
('pub_658', 'Popular Mechanics', 'tier1', 'tier1', 'Science', 1600, '3-5 days', 'Technology and engineering', '{"Engineering", "Technology", "DIY"}', 'https://popularmechanics.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_659', 'IEEE Spectrum', 'tier2', 'tier2', 'Science', 1400, '4-6 days', 'Engineering and technology', '{"Engineering", "Electronics", "Technology"}', 'https://spectrum.ieee.org', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),

-- Government & Politics (660-669)
('pub_660', 'Politico', 'tier1', 'tier1', 'Politics', 2400, '1-3 days', 'Political news and analysis', '{"Political News", "Policy", "Government"}', 'https://politico.com', 88, 85, 'United States', true, false, true, false, false, false, false, false, 90, true),
('pub_661', 'The Hill', 'tier1', 'tier1', 'Politics', 2200, '1-3 days', 'Congressional news', '{"Congress", "Policy", "Politics"}', 'https://thehill.com', 85, 82, 'United States', true, false, true, false, false, false, false, false, 87, true),
('pub_662', 'Roll Call', 'tier2', 'tier2', 'Politics', 1600, '2-4 days', 'Capitol Hill coverage', '{"Capitol Hill", "Congress", "Politics"}', 'https://rollcall.com', 79, 76, 'United States', true, false, true, false, false, false, false, false, 81, true),
('pub_663', 'Government Executive', 'tier2', 'tier2', 'Government', 1500, '3-5 days', 'Federal government news', '{"Federal Government", "Public Administration", "Policy"}', 'https://govexec.com', 77, 74, 'United States', true, false, true, false, false, false, false, false, 79, true),
('pub_664', 'Federal News Network', 'tier2', 'tier2', 'Government', 1300, '2-4 days', 'Federal government technology', '{"Federal IT", "Government Technology", "Policy"}', 'https://federalnewsnetwork.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_665', 'Defense News', 'tier2', 'tier2', 'Defense', 1700, '3-5 days', 'Defense industry news', '{"Defense", "Military", "Security"}', 'https://defensenews.com', 78, 75, 'United States', true, false, true, false, false, false, false, false, 80, true),
('pub_666', 'Federal Times', 'tier2', 'tier2', 'Government', 1200, '3-5 days', 'Federal employee news', '{"Federal Employees", "Government Jobs", "Benefits"}', 'https://federaltimes.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_667', 'NextGov', 'tier2', 'tier2', 'Government', 1400, '2-4 days', 'Government technology news', '{"Government Tech", "Digital Government", "Innovation"}', 'https://nextgov.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_668', 'Washington Technology', 'tier2', 'tier2', 'Government', 1100, '3-5 days', 'Government contracting', '{"Government Contracting", "Federal IT", "Procurement"}', 'https://washingtontechnology.com', 71, 68, 'United States', true, false, true, false, false, false, false, false, 73, true),
('pub_669', 'FCW', 'tier2', 'tier2', 'Government', 1300, '3-5 days', 'Federal computer week', '{"Federal IT", "Technology", "Government"}', 'https://fcw.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),

-- Energy & Environment (670-679)
('pub_670', 'Renewable Energy World', 'tier2', 'tier2', 'Energy', 1500, '3-5 days', 'Renewable energy industry', '{"Renewable Energy", "Solar", "Wind"}', 'https://renewableenergyworld.com', 76, 73, 'United States', true, false, true, false, false, false, false, false, 78, true),
('pub_671', 'Utility Dive', 'tier2', 'tier2', 'Energy', 1400, '2-4 days', 'Utility industry news', '{"Utilities", "Energy", "Grid"}', 'https://utilitydive.com', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_672', 'Energy Storage News', 'tier2', 'tier2', 'Energy', 1200, '3-5 days', 'Energy storage technology', '{"Energy Storage", "Batteries", "Grid Storage"}', 'https://energy-storage.news', 72, 69, 'United Kingdom', true, false, true, false, false, false, false, false, 74, true),
('pub_673', 'Solar Power World', 'tier2', 'tier2', 'Energy', 1300, '3-5 days', 'Solar energy industry', '{"Solar Energy", "Solar Power", "Renewable"}', 'https://solarpowerworldonline.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),
('pub_674', 'Wind Power Engineering', 'tier2', 'tier2', 'Energy', 1100, '4-6 days', 'Wind energy technology', '{"Wind Energy", "Wind Power", "Turbines"}', 'https://windpowerengineering.com', 71, 68, 'United States', true, false, true, false, false, false, false, false, 73, true),
('pub_675', 'Environmental Leader', 'tier2', 'tier2', 'Environment', 1200, '3-5 days', 'Environmental business news', '{"Environmental", "Sustainability", "Green Business"}', 'https://environmentalleader.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_676', 'GreenBiz', 'tier2', 'tier2', 'Environment', 1400, '3-5 days', 'Sustainable business', '{"Sustainability", "Green Business", "Environmental"}', 'https://greenbiz.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_677', 'Environmental Science & Technology', 'tier1', 'tier1', 'Environment', 1800, '5-7 days', 'Environmental science journal', '{"Environmental Science", "Research", "Technology"}', 'https://pubs.acs.org/journal/esthag', 82, 79, 'United States', true, false, true, false, false, false, false, false, 84, true),
('pub_678', 'CleanTechnica', 'tier2', 'tier2', 'Energy', 1000, '2-4 days', 'Clean technology news', '{"Clean Technology", "Electric Vehicles", "Solar"}', 'https://cleantechnica.com', 70, 67, 'United States', true, false, true, false, false, false, false, false, 72, true),
('pub_679', 'Energy News', 'tier2', 'tier2', 'Energy', 1300, '3-5 days', 'Energy industry news', '{"Energy Industry", "Oil & Gas", "Renewables"}', 'https://energynews.us', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),

-- Manufacturing & Industry (680-689)
('pub_680', 'Manufacturing.net', 'tier2', 'tier2', 'Manufacturing', 1300, '3-5 days', 'Manufacturing industry news', '{"Manufacturing", "Industrial", "Production"}', 'https://manufacturing.net', 74, 71, 'United States', true, false, true, false, false, false, false, false, 76, true),
('pub_681', 'Industry Week', 'tier2', 'tier2', 'Manufacturing', 1400, '3-5 days', 'Manufacturing leadership', '{"Manufacturing", "Operations", "Leadership"}', 'https://industryweek.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),
('pub_682', 'Plant Engineering', 'tier2', 'tier2', 'Manufacturing', 1200, '4-6 days', 'Plant operations and maintenance', '{"Plant Operations", "Maintenance", "Engineering"}', 'https://plantengineering.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_683', 'Assembly Magazine', 'tier2', 'tier2', 'Manufacturing', 1100, '3-5 days', 'Assembly and fastening', '{"Assembly", "Manufacturing", "Automation"}', 'https://assemblymag.com', 71, 68, 'United States', true, false, true, false, false, false, false, false, 73, true),
('pub_684', 'Control Engineering', 'tier2', 'tier2', 'Manufacturing', 1300, '4-6 days', 'Control and automation', '{"Control Systems", "Automation", "Engineering"}', 'https://controleng.com', 73, 70, 'United States', true, false, true, false, false, false, false, false, 75, true),
('pub_685', 'Modern Machine Shop', 'tier2', 'tier2', 'Manufacturing', 1200, '3-5 days', 'Machining and metalworking', '{"Machining", "Metalworking", "CNC"}', 'https://mmsonline.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_686', 'Packaging World', 'tier2', 'tier2', 'Manufacturing', 1100, '3-5 days', 'Packaging industry', '{"Packaging", "Food Packaging", "Industrial"}', 'https://packworld.com', 71, 68, 'United States', true, false, true, false, false, false, false, false, 73, true),
('pub_687', 'Quality Magazine', 'tier2', 'tier2', 'Manufacturing', 1000, '4-6 days', 'Quality control and testing', '{"Quality Control", "Testing", "Manufacturing"}', 'https://qualitymag.com', 70, 67, 'United States', true, false, true, false, false, false, false, false, 72, true),
('pub_688', 'Maintenance Technology', 'tier2', 'tier2', 'Manufacturing', 1200, '4-6 days', 'Maintenance and reliability', '{"Maintenance", "Reliability", "Asset Management"}', 'https://maintenancetechnology.com', 72, 69, 'United States', true, false, true, false, false, false, false, false, 74, true),
('pub_689', 'Supply Chain Dive', 'tier2', 'tier2', 'Manufacturing', 1400, '2-4 days', 'Supply chain management', '{"Supply Chain", "Logistics", "Manufacturing"}', 'https://supplychaindive.com', 75, 72, 'United States', true, false, true, false, false, false, false, false, 77, true),

-- Regional & International (690-699)
('pub_690', 'Toronto Star', 'tier1', 'tier1', 'News', 1800, '2-4 days', 'Canadian national newspaper', '{"Canadian News", "Politics", "Business"}', 'https://thestar.com', 80, 77, 'Canada', true, false, true, false, false, false, false, false, 82, true),
('pub_691', 'The Globe and Mail', 'tier1', 'tier1', 'News', 2000, '3-5 days', 'Canadian business newspaper', '{"Canadian Business", "Politics", "Finance"}', 'https://theglobeandmail.com', 82, 79, 'Canada', true, false, true, false, false, false, false, false, 84, true),
('pub_692', 'Sydney Morning Herald', 'tier1', 'tier1', 'News', 1900, '3-5 days', 'Australian newspaper', '{"Australian News", "Politics", "Business"}', 'https://smh.com.au', 81, 78, 'Australia', true, false, true, false, false, false, false, false, 83, true),
('pub_693', 'The Age', 'tier1', 'tier1', 'News', 1700, '3-5 days', 'Melbourne newspaper', '{"Australian News", "Melbourne", "Politics"}', 'https://theage.com.au', 79, 76, 'Australia', true, false, true, false, false, false, false, false, 81, true),
('pub_694', 'Times of India', 'tier1', 'tier1', 'News', 1600, '2-4 days', 'Indian national newspaper', '{"Indian News", "Business", "Technology"}', 'https://timesofindia.indiatimes.com', 78, 75, 'India', true, false, true, false, false, false, false, false, 80, true),
('pub_695', 'The Hindu', 'tier1', 'tier1', 'News', 1500, '3-5 days', 'Indian national newspaper', '{"Indian News", "Politics", "Business"}', 'https://thehindu.com', 77, 74, 'India', true, false, true, false, false, false, false, false, 79, true),
('pub_696', 'South China Morning Post', 'tier1', 'tier1', 'News', 2100, '3-5 days', 'Hong Kong newspaper', '{"Asian News", "China", "Business"}', 'https://scmp.com', 83, 80, 'Hong Kong', true, false, true, false, false, false, false, false, 85, true),
('pub_697', 'Japan Times', 'tier1', 'tier1', 'News', 1800, '3-5 days', 'Japanese English newspaper', '{"Japanese News", "Asian Business", "Technology"}', 'https://japantimes.co.jp', 80, 77, 'Japan', true, false, true, false, false, false, false, false, 82, true),
('pub_698', 'Bangkok Post', 'tier2', 'tier2', 'News', 1200, '3-5 days', 'Thai English newspaper', '{"Thai News", "Southeast Asia", "Business"}', 'https://bangkokpost.com', 74, 71, 'Thailand', true, false, true, false, false, false, false, false, 76, true),
('pub_699', 'Straits Times', 'tier1', 'tier1', 'News', 1700, '3-5 days', 'Singapore newspaper', '{"Singapore News", "Southeast Asia", "Business"}', 'https://straitstimes.com', 79, 76, 'Singapore', true, false, true, false, false, false, false, false, 81, true);