-- Insert starter package publications
INSERT INTO public.publications (
  name, price, category, tat_days, sponsored, indexed, dofollow_link, 
  location, erotic, health, cbd, crypto, gambling, website_url, 
  tier, type, description, features, is_active, popularity
) VALUES
('CEO Times', 97.00, 'Business', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://ceotimesmag.com', 'starter', 'standard', '', '{}', true, 50),
('USA News', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://usanews.com', 'starter', 'standard', '', '{}', true, 50),
('Mens Insider', 97.00, 'Lifestyle', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://mensinsider.com', 'starter', 'standard', '', '{}', true, 50),
('Today US', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://todaysusnews.com', 'starter', 'standard', '', '{}', true, 50),
('Biz Weekly', 97.00, 'Business', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://bizweekly.com', 'starter', 'standard', '', '{}', true, 50),
('NY Review', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://nyreview.com', 'starter', 'standard', '', '{}', true, 50),
('Womens Insider', 97.00, 'Lifestyle', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://womensinsider.com', 'starter', 'standard', '', '{}', true, 50),
('Biz Recap', 97.00, 'Business', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://bizrecap.com', 'starter', 'standard', '', '{}', true, 50),
('Good Morning US', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://goodmorningus.com', 'starter', 'standard', '', '{}', true, 50),
('Top Listings', 97.00, 'Business', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://toplistings.com', 'starter', 'standard', '', '{}', true, 50),
('Empire State Review', 97.00, 'Regional News', '3 business days', true, true, true, 'New York, USA', false, true, true, true, false, 'https://empirestatereview.com', 'starter', 'standard', '', '{}', true, 50),
('RENT Magazine', 97.00, 'Real Estate', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://rentmag.com', 'starter', 'standard', '', '{}', true, 50),
('Mens Newspaper', 97.00, 'Lifestyle/News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://mensnewspaper.com', 'starter', 'standard', '', '{}', true, 50),
('Digital Journal', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://www.digitaljournal.com', 'starter', 'standard', '', '{}', true, 50),
('Primetime Press', 97.00, 'Entertainment/News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://primetimepress.com', 'starter', 'standard', '', '{}', true, 50),
('Celeb Digest', 97.00, 'Entertainment', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://celebdigest.com', 'starter', 'standard', '', '{}', true, 50),
('Todays Read', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://todaysread.com', 'starter', 'standard', '', '{}', true, 50),
('Best Houses', 97.00, 'Real Estate', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://besthouses.com', 'starter', 'standard', '', '{}', true, 50),
('Juris Review', 97.00, 'Legal', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://jurisreview.com', 'starter', 'standard', '', '{}', true, 50),
('Mens Reporter', 97.00, 'Lifestyle/News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://mensreporter.com', 'starter', 'standard', '', '{}', true, 50),
('Golden State Review', 97.00, 'Regional News', '3 business days', true, true, true, 'California, USA', false, true, true, true, false, 'https://goldenstatereview.com', 'starter', 'standard', '', '{}', true, 50),
('The Leader Report', 97.00, 'Business/Leadership', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://theleaderreport.com', 'starter', 'standard', '', '{}', true, 50),
('Any Realty', 97.00, 'Real Estate', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://anyrealty.com', 'starter', 'standard', '', '{}', true, 50),
('Texas Recap', 97.00, 'Regional News', '3 business days', true, true, true, 'Texas, USA', false, true, true, true, false, 'https://texasrecap.com', 'starter', 'standard', '', '{}', true, 50),
('Artist Highlight', 97.00, 'Arts/Culture', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://artisthighlight.com', 'starter', 'standard', '', '{}', true, 50),
('Miami Highlight', 97.00, 'Regional Lifestyle', '3 business days', true, true, true, 'Florida, USA', false, true, true, true, false, 'https://miamihighlight.com', 'starter', 'standard', '', '{}', true, 50),
('Womens Reporter', 97.00, 'Lifestyle/News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://womensreporter.com', 'starter', 'standard', '', '{}', true, 50),
('A to Z Times', 97.00, 'News', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://atoztimes.com', 'starter', 'standard', '', '{}', true, 50),
('Artist Recap', 97.00, 'Arts/Culture', '3 business days', true, true, true, 'UNITED STATES', false, true, true, true, false, 'https://artistrecap.com', 'starter', 'standard', '', '{}', true, 50);