-- Continue adding more publications from the CSV file with unique IDs
-- Adding more unique publications
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('the-marketing-pilot-130', 'The Marketing Pilot', 125, 58, 42, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('next-web-blog-131', 'Next Web Blog', 125, 56, 41, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('the-ubj-132', 'The UBJ', 125, 60, 55, 'News', '1 Week', false, true, false, 'GLOBAL', false, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('crave-magazine-133', 'Crave Magazine', 125, 54, 40, 'News', '3 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('geek-insider-134', 'Geek Insider', 125, 47, 60, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('carousel-bondi-135', 'Carousel Bondi', 125, 15, 8, 'Lifestyle', '1-3 Days', false, true, true, 'AUSTRALIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('who-design-today-136', 'Who Design Today', 125, 19, 30, 'Lifestyle', '1-3 Days', false, true, true, 'AUSTRALIA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('crewlogout-137', 'Crewlogout', 125, 35, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('pie-mag-138', 'Pie Mag', 125, 33, 32, 'Real Estate', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('beautyation-139', 'Beautyation', 145, 55, 54, 'Fashion', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('wealth-tech-daily-140', 'Wealth Tech Daily', 150, 31, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('meditech-wire-141', 'Meditech Wire', 150, 31, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('sports-tech-today-142', 'Sports Tech Today', 150, 31, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('abc-money-143', 'ABC Money', 150, 67, 59, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('new-york-tech-144', 'New York Tech', 150, 57, 34, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('florida-reporter-145', 'Florida Reporter', 150, 37, 70, 'News', '1-3 Days', false, true, true, 'FLORIDA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('phlox-fitness-146', 'Phlox Fitness', 150, 5, 8, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('naluda-magazine-147', 'Naluda Magazine', 150, 59, 56, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('dollar-thinking-148', 'Dollar Thinking', 150, 1, 6, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('orangism-149', 'Orangism', 150, 58, 10, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('music-emu-150', 'Music Emu', 150, 3, 7, 'Music', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('web-law-info-151', 'Web Law Info', 150, 2, 1, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('luxury-la-mag-152', 'Luxury LA Mag', 150, 38, 32, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('pharmatech-news-153', 'Pharmatech News', 150, 34, 56, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('law-newsday-154', 'Law Newsday', 150, 34, 56, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('nohoarts-district-155', 'Nohoarts District', 150, 47, 64, 'News', '2-3 Days', false, true, true, 'UNITED STATES', true, true, true, true, true, true, 'standard', 'standard', '', '{}', 0),
('oh-my-dish-netherlands-156', 'Oh My Dish (Netherlands)', 150, 29, 28, 'Lifestyle', '3-5 Days', false, true, true, 'NETHERLANDS', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('girl-cooks-world-157', 'Girl Cooks World', 150, 49, 53, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, true, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('oh-my-dish-158', 'Oh My Dish', 150, 42, 52, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('our-kid-things-159', 'Our Kid Things', 150, 46, 49, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('new-york-street-food-160', 'New York Street Food', 150, 66, 45, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('techgyd-161', 'Techgyd', 150, 75, 55, 'Tech', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('hype-magazine-162', 'Hype Magazine', 150, 64, 72, 'Lifestyle', '1 Week', false, true, true, 'GLOBAL', false, true, true, true, false, true, 'standard', 'standard', '', '{}', 0),
('design-by-sully-163', 'Design By Sully', 150, 56, 55, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('shibley-smiles-164', 'Shibley Smiles', 150, 46, 54, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('my-face-hunter-165', 'My Face Hunter', 150, 72, 61, 'Lifestyle', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('get-world-beauty-166', 'Get World Beauty', 150, 55, 49, 'Fashion', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('innov8tiv-167', 'Innov8tiv', 150, 48, 62, 'Tech', '3 Days', false, true, true, 'UNITED STATES', false, false, false, true, false, true, 'standard', 'standard', '', '{}', 0),
('the-boss-magazine-168', 'The Boss Magazine', 150, 51, 73, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('homes-creative-169', 'Homes Creative', 150, 52, 35, 'Real Estate', '3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0);