-- Continue adding more publications from CSV - Batch 8
-- Adding lifestyle, entertainment, and international publications
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('airbnb-newsroom-500', 'Airbnb Newsroom', 250, 82, 81, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('tesla-blog-501', 'Tesla Blog', 350, 87, 86, 'Tech', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('spacex-news-502', 'SpaceX News', 400, 88, 87, 'Tech', '3-6 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('netflix-media-503', 'Netflix Media', 300, 85, 84, 'Entertainment', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('disney-news-504', 'Disney News', 350, 86, 85, 'Entertainment', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('warner-bros-news-505', 'Warner Bros News', 275, 83, 82, 'Entertainment', '1-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('universal-pictures-506', 'Universal Pictures', 300, 84, 83, 'Entertainment', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('paramount-news-507', 'Paramount News', 250, 81, 80, 'Entertainment', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('sony-pictures-508', 'Sony Pictures', 275, 82, 81, 'Entertainment', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('vogue-509', 'Vogue', 500, 89, 88, 'Fashion', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('elle-510', 'Elle', 400, 87, 86, 'Fashion', '1-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('harpers-bazaar-511', 'Harpers Bazaar', 450, 88, 87, 'Fashion', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('marie-claire-512', 'Marie Claire', 350, 85, 84, 'Fashion', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('cosmopolitan-513', 'Cosmopolitan', 375, 86, 85, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('glamour-514', 'Glamour', 325, 84, 83, 'Fashion', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('vanity-fair-515', 'Vanity Fair', 600, 91, 90, 'Lifestyle', '3-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('gq-magazine-516', 'GQ Magazine', 450, 87, 86, 'Lifestyle', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('esquire-517', 'Esquire', 400, 86, 85, 'Lifestyle', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('mens-health-518', 'Mens Health', 350, 84, 83, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('womens-health-519', 'Womens Health', 350, 84, 83, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('fitness-magazine-520', 'Fitness Magazine', 275, 81, 80, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('shape-magazine-521', 'Shape Magazine', 300, 82, 81, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('self-magazine-522', 'Self Magazine', 325, 83, 82, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('real-simple-523', 'Real Simple', 275, 80, 79, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('better-homes-gardens-524', 'Better Homes & Gardens', 300, 82, 81, 'Lifestyle', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('good-housekeeping-525', 'Good Housekeeping', 325, 83, 82, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('house-beautiful-526', 'House Beautiful', 350, 84, 83, 'Lifestyle', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('architectural-digest-527', 'Architectural Digest', 450, 87, 86, 'Lifestyle', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('elle-decor-528', 'Elle Decor', 375, 85, 84, 'Lifestyle', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('food-wine-529', 'Food & Wine', 325, 83, 82, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('bon-appetit-530', 'Bon Appetit', 350, 84, 83, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('cooking-light-531', 'Cooking Light', 275, 81, 80, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('epicurious-532', 'Epicurious', 250, 79, 78, 'Lifestyle', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('allrecipes-533', 'Allrecipes', 200, 77, 76, 'Lifestyle', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('food-network-534', 'Food Network', 300, 82, 81, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('travel-leisure-535', 'Travel + Leisure', 400, 86, 85, 'Lifestyle', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('conde-nast-traveler-536', 'Conde Nast Traveler', 450, 87, 86, 'Lifestyle', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('national-geographic-537', 'National Geographic', 500, 90, 89, 'Lifestyle', '3-5 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 92),
('smithsonian-magazine-538', 'Smithsonian Magazine', 400, 85, 84, 'Lifestyle', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('scientific-american-539', 'Scientific American', 350, 84, 83, 'Science', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86);