-- Final batch - Adding more publications to complete the collection
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('engadget-320', 'Engadget', 350, 84, 82, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('the-verge-321', 'The Verge', 400, 88, 86, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('ars-technica-322', 'Ars Technica', 350, 83, 81, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('gizmodo-323', 'Gizmodo', 300, 82, 80, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('lifehacker-324', 'Lifehacker', 250, 79, 77, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 79),
('buzzfeed-325', 'BuzzFeed', 300, 85, 83, 'Entertainment', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('huffington-post-326', 'Huffington Post', 350, 87, 85, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('vox-327', 'Vox', 300, 84, 82, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('slate-328', 'Slate', 250, 81, 79, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 81),
('politico-329', 'Politico', 400, 86, 84, 'Political', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('axios-330', 'Axios', 350, 83, 81, 'News', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('the-hill-331', 'The Hill', 300, 82, 80, 'Political', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('marketwatch-332', 'MarketWatch', 350, 84, 82, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('cnbc-premium-333', 'CNBC Premium', 450, 89, 87, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('fox-business-334', 'Fox Business', 300, 81, 79, 'Business', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 81),
('espn-335', 'ESPN', 400, 88, 86, 'Sports', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('sports-illustrated-336', 'Sports Illustrated', 350, 85, 83, 'Sports', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('variety-337', 'Variety', 350, 84, 82, 'Entertainment', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('hollywood-reporter-338', 'Hollywood Reporter', 300, 83, 81, 'Entertainment', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('entertainment-weekly-339', 'Entertainment Weekly', 250, 80, 78, 'Entertainment', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 80),
('rolling-stone-340', 'Rolling Stone', 400, 86, 84, 'Music', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('billboard-341', 'Billboard', 350, 84, 82, 'Music', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('pitchfork-342', 'Pitchfork', 300, 81, 79, 'Music', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 81),
('people-magazine-343', 'People Magazine', 300, 82, 80, 'Entertainment', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('us-weekly-344', 'Us Weekly', 250, 79, 77, 'Entertainment', '1-3 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 79),
('vogue-345', 'Vogue', 500, 89, 87, 'Fashion', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('elle-346', 'Elle', 400, 86, 84, 'Fashion', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('harpers-bazaar-347', 'Harpers Bazaar', 450, 87, 85, 'Fashion', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('cosmopolitan-348', 'Cosmopolitan', 300, 83, 81, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('marie-claire-349', 'Marie Claire', 350, 84, 82, 'Fashion', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('womens-health-350', 'Womens Health', 300, 82, 80, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('mens-health-351', 'Mens Health', 300, 82, 80, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('gq-magazine-352', 'GQ Magazine', 400, 85, 83, 'Fashion', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('esquire-353', 'Esquire', 350, 84, 82, 'Lifestyle', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('architectural-digest-354', 'Architectural Digest', 400, 86, 84, 'Real Estate', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('food-wine-355', 'Food & Wine', 300, 83, 81, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 83),
('bon-appetit-356', 'Bon Appetit', 350, 84, 82, 'Lifestyle', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('travel-leisure-357', 'Travel + Leisure', 350, 84, 82, 'Lifestyle', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('conde-nast-traveler-358', 'Conde Nast Traveler', 400, 86, 84, 'Lifestyle', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('national-geographic-359', 'National Geographic', 500, 90, 88, 'Science', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90);