-- Continue adding more major publications from CSV - Batch 6
-- Adding high-authority publications and remaining entries
INSERT INTO public.publications (
  external_id,
  name,
  price,
  da_score,
  dr_score,
  category,
  tat_days,
  sponsored,
  indexed,
  dofollow_link,
  location,
  erotic,
  health,
  cbd,
  crypto,
  gambling,
  is_active,
  type,
  tier,
  description,
  features,
  popularity
) VALUES 
('i-love-south-africa-280', 'I Love South Africa', 200, 18, 56, 'News', '3-5 Days', false, true, true, 'AFRICA', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('mom-the-mag-281', 'Mom The Mag', 200, 56, 35, 'Lifestyle', '1-3 Days', false, true, false, 'UNITED STATES', false, true, true, false, false, true, 'standard', 'standard', '', '{}', 0),
('edm-sauce-282', 'EDM Sauce', 200, 76, 60, 'Music', '3 Days', false, true, false, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 75),
('we-rave-you-283', 'We Rave You', 200, 52, 62, 'Music', '1 Week', false, true, false, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('deadline-new-284', 'Deadline New', 200, 74, 68, 'News', '3 Days', false, true, false, 'GLOBAL', false, true, true, true, true, true, 'premium', 'premium', '', '{}', 70),
('allhiphop-285', 'AllHipHop', 200, 73, 73, 'Music', '1 Week', false, true, false, 'GLOBAL', false, true, true, true, false, true, 'premium', 'premium', '', '{}', 73),
('art-daily-286', 'Art Daily', 200, 65, 79, 'Entertainment', '1-3 Days', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 65),
('patch-com-287', 'Patch.com', 200, 91, 90, 'News', '3-5 Days', true, true, false, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('good-men-project-288', 'Good Men Project', 200, 82, 79, 'News', '1 Week', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('ny-tech-media-289', 'NY Tech Media', 200, 34, 34, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('coin-review-news-290', 'Coin Review News', 250, 29, 39, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('startupbooted-291', 'StartUpBooted.com', 250, 55, 67, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('percentagecalculatorshub-292', 'PercentageCalculatorsHub.com', 250, 53, 67, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('snapchatplanet-293', 'SnapchatPlanet.com', 250, 43, 64, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('growthnavigate-294', 'GrowthNavigate.com', 250, 50, 61, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('ib-times-ap-295', 'IB Times (AP)', 250, 73, 72, 'Business', '1 Week', false, true, false, 'ASIA PACIFIC', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 73),
('cultr-magazine-296', 'Cultr Magazine', 250, 34, 48, 'Music', '1 Week', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'standard', 'standard', '', '{}', 0),
('silicon-angle-297', 'Silicon Angle', 300, 82, 84, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 82),
('yahoo-finance-298', 'Yahoo Finance', 400, 92, 90, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 92),
('techcrunch-299', 'TechCrunch', 500, 93, 91, 'Tech', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('reuters-300', 'Reuters', 600, 95, 94, 'News', '1-2 Weeks', false, true, true, 'GLOBAL', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 95),
('bloomberg-301', 'Bloomberg', 650, 94, 93, 'Business', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('washington-post-302', 'Washington Post', 550, 93, 92, 'News', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('usa-today-303', 'USA Today', 450, 91, 89, 'News', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('time-magazine-304', 'Time Magazine', 700, 94, 93, 'News', '2-4 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('newsweek-305', 'Newsweek', 500, 89, 87, 'News', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 89),
('business-insider-306', 'Business Insider', 450, 87, 85, 'Business', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('entrepreneur-magazine-307', 'Entrepreneur Magazine', 400, 84, 82, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 84),
('fast-company-308', 'Fast Company', 500, 86, 84, 'Business', '1-2 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('inc-magazine-309', 'Inc Magazine', 450, 85, 83, 'Business', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('fortune-magazine-310', 'Fortune Magazine', 600, 90, 88, 'Business', '2-3 Weeks', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 90),
('the-guardian-311', 'The Guardian', 500, 93, 91, 'News', '1-2 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 93),
('bbc-news-312', 'BBC News', 550, 94, 92, 'News', '1-2 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 94),
('financial-times-313', 'Financial Times', 650, 92, 90, 'Business', '1-2 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 92),
('telegraph-314', 'The Telegraph', 450, 88, 86, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 88),
('independent-315', 'The Independent', 400, 86, 84, 'News', '3-5 Days', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86),
('economist-316', 'The Economist', 700, 91, 89, 'Business', '2-4 Weeks', false, true, true, 'UNITED KINGDOM', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 91),
('cnet-317', 'CNET', 300, 85, 83, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 85),
('wired-magazine-318', 'Wired Magazine', 400, 87, 85, 'Tech', '1 Week', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 87),
('mashable-319', 'Mashable', 350, 86, 84, 'Tech', '3-5 Days', false, true, true, 'UNITED STATES', false, false, false, false, false, true, 'premium', 'premium', '', '{}', 86);