// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxjjedeqnbsyqkahsjlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4amplZGVxbmJzeXFrYWhzamxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTg5MjksImV4cCI6MjA3MzE5NDkyOX0.BXEhZGcd0Nj-EnNG570oDYzxmkHy3z5gT9_4UUG5F-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});